import { Candidate } from "@/lib/types/candidate"

export const sampleCandidates: Candidate[] = [
  {
    id: "1",
    name: "John Doe",
    currentJobTitle: "Senior Frontend Developer",
    postingTitle: "React Developer",
    email: "john.doe@email.com",
    mobileNo: "+1-555-0123",
    cnic: "12345-6789012-3",
    currentSalary: 75000,
    expectedSalary: 85000,
    city: "New York",
    githubUrl: "https://github.com/johndoe",
    linkedinUrl: "https://linkedin.com/in/johndoe",
    source: "LinkedIn",
    status: "active",
    resume: "john_doe_resume.pdf",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15")
  },
  {
    id: "2", 
    name: "Sarah Wilson",
    currentJobTitle: "UI/UX Designer",
    postingTitle: "Senior Designer", 
    email: "sarah.wilson@email.com",
    mobileNo: "+1-555-0124",
    cnic: "12345-6789012-4",
    currentSalary: 65000,
    expectedSalary: 75000,
    city: "San Francisco",
    githubUrl: "https://github.com/sarahwilson",
    linkedinUrl: "https://linkedin.com/in/sarahwilson",
    source: "Company Website",
    status: "interviewed",
    resume: "sarah_wilson_resume.pdf",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-20")
  },
  {
    id: "3",
    name: "Michael Johnson",
    currentJobTitle: "Full Stack Engineer",
    postingTitle: "Senior Full Stack Developer",
    email: "michael.johnson@email.com", 
    mobileNo: "+1-555-0125",
    cnic: "12345-6789012-5",
    currentSalary: 80000,
    expectedSalary: 95000,
    city: "Austin",
    githubUrl: "https://github.com/michaeljohnson",
    linkedinUrl: "https://linkedin.com/in/michaeljohnson",
    source: "Referral",
    status: "shortlisted",
    resume: "michael_johnson_resume.pdf",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-22")
  },
  {
    id: "4",
    name: "Emily Chen",
    currentJobTitle: "DevOps Engineer",
    postingTitle: "Senior DevOps Engineer",
    email: "emily.chen@email.com",
    mobileNo: "+1-555-0126", 
    cnic: "12345-6789012-6",
    currentSalary: 85000,
    expectedSalary: 100000,
    city: "Seattle",
    githubUrl: "https://github.com/emilychen",
    linkedinUrl: "https://linkedin.com/in/emilychen",
    source: "Indeed",
    status: "pending",
    resume: "emily_chen_resume.pdf",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-18")
  },
  {
    id: "5",
    name: "David Rodriguez",
    currentJobTitle: "Backend Developer",
    postingTitle: "Node.js Developer",
    email: "david.rodriguez@email.com",
    mobileNo: "+1-555-0127",
    cnic: "12345-6789012-7", 
    currentSalary: 70000,
    expectedSalary: 80000,
    city: "Denver",
    githubUrl: "https://github.com/davidrodriguez",
    linkedinUrl: "https://linkedin.com/in/davidrodriguez",
    source: "Stack Overflow Jobs",
    status: "active",
    resume: "david_rodriguez_resume.pdf",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-25")
  },
  {
    id: "6",
    name: "Lisa Thompson",
    currentJobTitle: "Product Manager",
    postingTitle: "Senior Product Manager",
    email: "lisa.thompson@email.com",
    mobileNo: "+1-555-0128",
    cnic: "12345-6789012-8",
    currentSalary: 95000,
    expectedSalary: 110000,
    city: "Boston",
    linkedinUrl: "https://linkedin.com/in/lisathompson",
    source: "AngelList", 
    status: "hired",
    resume: "lisa_thompson_resume.pdf",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-28")
  },
  {
    id: "7",
    name: "James Kim",
    currentJobTitle: "Data Scientist",
    postingTitle: "Senior Data Scientist",
    email: "james.kim@email.com",
    mobileNo: "+1-555-0129",
    cnic: "12345-6789012-9",
    currentSalary: 90000,
    expectedSalary: 105000,
    city: "Chicago", 
    githubUrl: "https://github.com/jameskim",
    linkedinUrl: "https://linkedin.com/in/jameskim",
    source: "Glassdoor",
    status: "rejected",
    resume: "james_kim_resume.pdf",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-30")
  },
  {
    id: "8",
    name: "Maria Garcia",
    currentJobTitle: "QA Engineer", 
    postingTitle: "Senior QA Engineer",
    email: "maria.garcia@email.com",
    mobileNo: "+1-555-0130",
    cnic: "12345-6789012-0",
    currentSalary: 65000,
    expectedSalary: 75000,
    city: "Miami",
    githubUrl: "https://github.com/mariagarcia",
    linkedinUrl: "https://linkedin.com/in/mariagarcia",
    source: "Company Website",
    status: "withdrawn",
    resume: "maria_garcia_resume.pdf",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  }
]


