import { Candidate } from "@/lib/types/candidate"

export const sampleCandidates: Candidate[] = [
  {
    id: "1",
    name: "Umais Rasheed",
    currentJobTitle: "React Native Developer",
    postingTitle: null,
    email: "mianumais1997@gmail.com ",
    mobileNo: "0321-6781277",
    cnic: "61101-83552611",
    currentSalary: null,
    expectedSalary: 1100000,
    city: "Islamabad",
    githubUrl: "https://github.com/umaiss/",
    linkedinUrl: "https://www.linkedin.com/in/umais-rasheed/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/:b:/p/raahim_z/IQByxRtJfd73RJ1W23nZsbCfAdTRvNSC73afmp0WK8D1IT4?e=tpQPwf",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15")
  },
  {
    id: "2", 
    name: "Abdul Rehman",
    currentJobTitle: "Business Development Executive",
    postingTitle: null, 
    email: "abdulrehman6149@gmail.com",
    mobileNo: "0316-7655438",
    cnic: "34202-61369325",
    currentSalary: null,
    expectedSalary: null,
    city: "Rawalpindi",
    githubUrl: null,
    linkedinUrl: "https://www.linkedin.com/in/abdulrehman6149/",
    source: "DPL Employee",
    status: "hired",
    resume: null,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-20")
  },
  {
    id: "3",
    name: "Muhammad Ahmad",
    currentJobTitle: "Software Engineer",
    postingTitle: null,
    email: "muhammadahmad23664@gmail.com",
    mobileNo: "0331-5152107",
    cnic: "61101-45606043",
    currentSalary: null,
    expectedSalary: 10000000,
    city: "Islamabad",
    githubUrl: "https://github.com/MA23664",
    linkedinUrl: "https://www.linkedin.com/in/muhammad-ahmad-1b8aa1241/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FMuhammad%20Ahmad%20CV%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-22")
  },
  {
    id: "4",
    name: "Daniyal Rauf",
    currentJobTitle: "Software Engineer (React Native)",
    postingTitle: null,
    email: "daniyalrathore14@gmail.com",
    mobileNo: "0344-6021955", 
    cnic: "34101-07389247",
    currentSalary: null,
    expectedSalary: 360000,
    city: "Islamabad",
    githubUrl: "https://github.com/emilychen",
    linkedinUrl: "https://www.linkedin.com/in/daniyal-rauf-rathore-a21ab31a6/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FDRR%20CV%20%283%29%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-18")
  },
  {
    id: "5",
    name: "Aliyan Latif",
    currentJobTitle: "Software Engineer (React Native)",
    postingTitle: null,
    email: "aliyanlatif1122@gmail.com",
    mobileNo: "0331-5673669",
    cnic: "61101-49523849", 
    currentSalary: null,
    expectedSalary: 500000,
    city: "Islamabad",
    githubUrl: "https://github.com/aliyanlatif",
    linkedinUrl: "https://www.linkedin.com/in/aliyan-latif-4056171a7/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FAliyan%20Latif%27s%20Resume%202%20%282%29%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-25")
  },
  {
    id: "6",
    name: "Ubaid Khan",
    currentJobTitle: "PERN Stack Developer",
    postingTitle: null,
    email: "dev.ubd99@gmail.com",
    mobileNo: "0315-6258145",
    cnic: "17301-49200307",
    currentSalary: null,
    expectedSalary: 200000,
    city: "Islamabad",
    linkedinUrl: "https://www.linkedin.com/in/ubd99/",
    source: "DPL Employee", 
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FCV%20UBD%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-28")
  },
  {
    id: "7",
    name: "Sohaib Qamar",
    currentJobTitle: "Sr. Embedded Firmware Engineer",
    postingTitle: null,
    email: "qamarsohaib86@gmail.com",
    mobileNo: "0346-4320467",
    cnic: "3705-98857439",
    currentSalary: null,
    expectedSalary: 1000000,
    city: "Islamabad", 
    githubUrl: null,
    linkedinUrl: "https://www.linkedin.com/in/sohaibqamar86/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FSohaib%20Resume%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-30")
  },
  {
    id: "8",
    name: "Iqra Munawar",
    currentJobTitle: "Graphic Designer", 
    postingTitle: null,
    email: "iqramunawar21k8@gmail.com",
    mobileNo: "0314-7146674",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: null,
    linkedinUrl: "https://www.linkedin.com/in/iqra-munawar-a8342b187/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FIqra%5FResume%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "9",
    name: "Ahmed Rehman",
    currentJobTitle: "Android Developer", 
    postingTitle: null,
    email: "ahmedrehman921@gmail.com",
    mobileNo: "0312-7113699",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: "https://ahmed4240.github.io/",
    linkedinUrl: "https://www.linkedin.com/in/ahmed-rehman-b73b11123/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=rehm&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FAhmed%2DRehman%2DAndroid%2DCV%20%282%29%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "10",
    name: "Izza Shahzad",
    currentJobTitle: "IT Intern", 
    postingTitle: null,
    email: "Izzashahzad2003@gmail.com",
    mobileNo: "0336-5544454",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Rawalpindi",
    githubUrl: "https://github.com/izza013",
    linkedinUrl: "https://www.linkedin.com/in/izza-shahzad-b43273267/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FIZZA%20SHAHZAD%20CV%20AI%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "11",
    name: "Sara Nayab",
    currentJobTitle: "QA Analyst (Internship)", 
    postingTitle: null,
    email: "saraawan37405@gmail.com",
    mobileNo: "0346-0562771",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: null,
    linkedinUrl: "https://www.linkedin.com/in/sara-nayab",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FSara%20Nayab%5FResume%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "12",
    name: "Umair Tahir",
    currentJobTitle: "AngularJS Intern", 
    postingTitle: null,
    email: "umairmt18@gmail.com",
    mobileNo: "+92 349 4542278",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Rawalpindi",
    githubUrl: null,
    linkedinUrl: null,
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FUmair%20Tahir%20Resume%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "13",
    name: "Mahnoor Moosa Raza",
    currentJobTitle: "QA (Intern)", 
    postingTitle: null,
    email: "mahnoorraza477@gmail.com",
    mobileNo: "0333-3777526",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: "https://github.com/mahnoorraza",
    linkedinUrl: null,
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=mahnoor&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FMahnoor%20SQA%5FICV%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "14",
    name: "Umair Shahid",
    currentJobTitle: "Frontend Developer", 
    postingTitle: null,
    email: "shahidumair622@gmail.com",
    mobileNo: "+92 321 5215701",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: null,
    linkedinUrl: "https://www.linkedin.com/in/umair-shahid-b72086243",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=resume&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FResume%20%2816%29%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "15",
    name: "Sufi Hassan Asim",
    currentJobTitle: "Developer & AI Consultant", 
    postingTitle: null,
    email: "hassanasim337@gmail.com",
    mobileNo: "+92 330 5241433",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: "https://github.com/Hassan-asim",
    linkedinUrl: "https://www.linkedin.com/in/sufi-hassan-asim",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=sufi&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FSufi%20Hassan%20Asim%20resume%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "16",
    name: "Abdullah Amjad",
    currentJobTitle: "QA Engineer", 
    postingTitle: null,
    email: "abdullahamjad1212@gmail.com",
    mobileNo: "+92 311 5428964",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Rawalpindi",
    githubUrl: null,
    linkedinUrl: null,
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=abdullah&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FCV%5FAbdullah%2DAmjad%5FQA%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "17",
    name: "Mohid Anwar",
    currentJobTitle: "Graphic Designer", 
    postingTitle: null,
    email: "mohid.anwar@gmail.com",
    mobileNo: "+92 335 0122012",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: "https://github.com/Mohid-Anwar",
    linkedinUrl: "https://www.linkedin.com/in/mohid-anwar",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=mohid&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FMohid%20Anwar%20Resume%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "18",
    name: "Tassaduq Hussain",
    currentJobTitle: "Senior Software Engineer", 
    postingTitle: null,
    email: "tassaduq955@gmail.com",
    mobileNo: "+92 301 8712103",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: "https://github.com/tassaduq-qbatch",
    linkedinUrl: "https://www.linkedin.com/in/tassaduq-hussain-253630131/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=tassaduq&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FTassaduq%20Hussain%2DResume%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "19",
    name: "Aaqib Khan",
    currentJobTitle: "Full Stack Developer", 
    postingTitle: null,
    email: "aaqibkhanniazi91@gmail.com",
    mobileNo: "+92 302 7674359",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: null,
    linkedinUrl: "http://www.linkedin.com/in/aaqib-khan-niazi-a9764b156",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/query?q=aaqib&searchScope=all&id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FAaqib%20Khan%20resume%281%29%2Epdf&parentview=7",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  },
  {
    id: "20",
    name: "Mahir Lodhi",
    currentJobTitle: "Videographer / Production (Freelance)", 
    postingTitle: null,
    email: "mahirlodhi98@gmail.com",
    mobileNo: "0334-5505730",
    cnic: null,
    currentSalary: null,
    expectedSalary: null,
    city: "Islamabad",
    githubUrl: null,
    linkedinUrl: "https://www.instagram.com/cameraholic01/",
    source: "DPL Employee",
    status: "hired",
    resume: "https://dplit-my.sharepoint.com/my?id=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments%2FIqra%5FResume%2Epdf&parent=%2Fpersonal%2Fraahim%5Fz%5Fdplit%5Fcom%2FDocuments",
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2024-02-01")
  }
]


