import { Certification } from "@/lib/types/certification"

export const sampleCertifications: Certification[] = [
  {
    id: "cert-001",
    certificationName: "AWS Certified Solutions Architect",
    issuingBody: "Amazon Web Services",
    certificationLevel: "Professional",
    createdAt: new Date("2023-08-16"),
    updatedAt: new Date("2023-08-16"),
  },
  {
    id: "cert-002", 
    certificationName: "Microsoft Azure Fundamentals",
    issuingBody: "Microsoft Corporation",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-06-21"),
    updatedAt: new Date("2023-06-21"),
  },
  {
    id: "cert-003",
    certificationName: "Google Cloud Professional Cloud Architect",
    issuingBody: "Google Cloud",
    certificationLevel: "Professional",
    createdAt: new Date("2023-03-13"),
    updatedAt: new Date("2023-03-13"),
  },
  {
    id: "cert-004",
    certificationName: "Certified Kubernetes Administrator",
    issuingBody: "Cloud Native Computing Foundation",
    certificationLevel: "Professional",
    createdAt: new Date("2023-01-06"),
    updatedAt: new Date("2023-01-06"),
  },
  {
    id: "cert-005",
    certificationName: "Docker Certified Associate",
    issuingBody: "Docker Inc.",
    certificationLevel: "Associate",
    createdAt: new Date("2022-11-19"),
    updatedAt: new Date("2022-11-19"),
  },
  {
    id: "cert-006",
    certificationName: "Terraform Associate",
    issuingBody: "HashiCorp",
    certificationLevel: "Associate",
    createdAt: new Date("2023-09-29"),
    updatedAt: new Date("2023-09-29"),
  },
  {
    id: "cert-007",
    certificationName: "CompTIA Security+",
    issuingBody: "CompTIA",
    certificationLevel: "Associate",
    createdAt: new Date("2023-04-11"),
    updatedAt: new Date("2023-04-11"),
  },
  {
    id: "cert-008",
    certificationName: "Certified Information Systems Security Professional",
    issuingBody: "ISC2",
    certificationLevel: "Expert",
    createdAt: new Date("2022-07-23"),
    updatedAt: new Date("2022-07-23"),
  },
  {
    id: "cert-009",
    certificationName: "Oracle Cloud Infrastructure Foundations",
    issuingBody: "Oracle Corporation",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-12-04"),
    updatedAt: new Date("2023-12-04"),
  },
  {
    id: "cert-010",
    certificationName: "Red Hat Certified Engineer",
    issuingBody: "Red Hat Inc.",
    certificationLevel: "Professional",
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2023-02-15"),
  },
  {
    id: "cert-011",
    certificationName: "Certified Scrum Master",
    issuingBody: "Scrum Alliance",
    certificationLevel: "Associate",
    createdAt: new Date("2023-10-09"),
    updatedAt: new Date("2023-10-09"),
  },
  {
    id: "cert-012",
    certificationName: "MongoDB Certified Developer",
    issuingBody: "MongoDB Inc.",
    certificationLevel: "Associate",
    createdAt: new Date("2022-12-13"),
    updatedAt: new Date("2022-12-13"),
  },
  {
    id: "cert-013",
    certificationName: "Certified Ethical Hacker",
    issuingBody: "EC-Council",
    certificationLevel: "Professional",
    createdAt: new Date("2023-05-18"),
    updatedAt: new Date("2023-05-18"),
  },
  {
    id: "cert-014",
    certificationName: "PMP - Project Management Professional",
    issuingBody: "Project Management Institute",
    certificationLevel: "Professional",
    createdAt: new Date("2023-07-25"),
    updatedAt: new Date("2023-07-25"),
  },
  {
    id: "cert-015",
    certificationName: "ITIL Foundation",
    issuingBody: "AXELOS",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  }
]
