import { Certification } from "@/lib/types/certification"

export const sampleCertifications: Certification[] = [
  {
    id: "cert-001",
    certificationName: "Foundations of Project Management",
    issuingBody: "Coursera",
    certificationLevel: "Professional",
    createdAt: new Date("2023-08-16"),
    updatedAt: new Date("2023-08-16"),
  },
  {
    id: "cert-002", 
    certificationName: "Supervised Machine Learning: Regression and Classification",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-06-21"),
    updatedAt: new Date("2023-06-21"),
  },
  {
    id: "cert-003",
    certificationName: "Project Initiation: Starting a Successful Project",
    issuingBody: "Coursera",
    certificationLevel: "Professional",
    createdAt: new Date("2023-03-13"),
    updatedAt: new Date("2023-03-13"),
  },
  {
    id: "cert-004",
    certificationName: "Project Planning: Putting It All Together",
    issuingBody: "Coursera",
    certificationLevel: "Professional",
    createdAt: new Date("2023-01-06"),
    updatedAt: new Date("2023-01-06"),
  },
  {
    id: "cert-005",
    certificationName: "Foundations of Cybersecurity",
    issuingBody: "Coursera",
    certificationLevel: "Associate",
    createdAt: new Date("2022-11-19"),
    updatedAt: new Date("2022-11-19"),
  },
  {
    id: "cert-006",
    certificationName: "Machine Learning",
    issuingBody: "Coursera",
    certificationLevel: "Associate",
    createdAt: new Date("2023-09-29"),
    updatedAt: new Date("2023-09-29"),
  },
  {
    id: "cert-007",
    certificationName: "Introduction to Cybersecurity Tools & Cyberattacks",
    issuingBody: "Coursera",
    certificationLevel: "Associate",
    createdAt: new Date("2023-04-11"),
    updatedAt: new Date("2023-04-11"),
  },
  {
    id: "cert-008",
    certificationName: "Advanced Learning Algorithms",
    issuingBody: "Coursera",
    certificationLevel: "Expert",
    createdAt: new Date("2022-07-23"),
    updatedAt: new Date("2022-07-23"),
  },
  {
    id: "cert-009",
    certificationName: "Create a Website Using Wordpress : Free Hosting & Sub-domain",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-12-04"),
    updatedAt: new Date("2023-12-04"),
  },
  {
    id: "cert-010",
    certificationName: "Getting started with Flutter Development",
    issuingBody: "Coursera",
    certificationLevel: "Professional",
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2023-02-15"),
  },
  {
    id: "cert-011",
    certificationName: "Programming for Everybody (Getting Started with Python)",
    issuingBody: "Coursera",
    certificationLevel: "Associate",
    createdAt: new Date("2023-10-09"),
    updatedAt: new Date("2023-10-09"),
  },
  {
    id: "cert-012",
    certificationName: "Hands-on Introduction to Linux Commands and Shell Scripting",
    issuingBody: "Coursera",
    certificationLevel: "Associate",
    createdAt: new Date("2022-12-13"),
    updatedAt: new Date("2022-12-13"),
  },
  {
    id: "cert-013",
    certificationName: "Flutter Development",
    issuingBody: "BitDegree",
    certificationLevel: "Professional",
    createdAt: new Date("2023-05-18"),
    updatedAt: new Date("2023-05-18"),
  },
  {
    id: "cert-014",
    certificationName: "Game Design and Development 2: 2D Platformer",
    issuingBody: "Coursera",
    certificationLevel: "Professional",
    createdAt: new Date("2023-07-25"),
    updatedAt: new Date("2023-07-25"),
  },
  {
    id: "cert-015",
    certificationName: "Game Design and Development 1: 2D Shooter",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Python for Data Science, AI & Development",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "AI For Everyone",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Scrum Fundamentals Certified (SFC)",
    issuingBody: "Scrumstudy",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "CS-860 Artificial Intelligence",
    issuingBody: "NUST, Islamabad",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "CS-871 Machine Learning",
    issuingBody: "NUST, Islamabad",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Coursera Course Certifications",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Google Developer Student Club (Core Team Member)",
    issuingBody: "GDSC",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "RMA Process for Redline AN-80i",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Intellect Cameras Management Software Training",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Raspberry Pi, Web Server Training",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Android Development",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Android Development",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Cybersecurity Fundamentals",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Generative AI Training",
    issuingBody: "PAKAngles",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Introduction to Machine Learning",
    issuingBody: "Microsoft",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Six Sigma Principles",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Agile Project Management",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "ISO 9001:2015 (QMS)",
    issuingBody: "CPD Accredited",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "ISQI A4Q Selenium Certified Tester",
    issuingBody: "Certified",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "ISTQB CT-FL",
    issuingBody: "American Software Testing Board",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Test Automation with Cypress",
    issuingBody: "10Pearls University",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Scrum Foundation Professional Certificate (SFPC)",
    issuingBody: "CertiProf",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "ISTQB Agile Tester Extension (CTFL-AT)",
    issuingBody: "Certified",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Exploring service APIs through test automation",
    issuingBody: "Test Automation University",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "White Belt Six Sigma",
    issuingBody: "Six Sigma Council",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "TOSCA Test Automation Specialist Level 1",
    issuingBody: "Certified",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Meta Front-End Developer",
    issuingBody: "Coursera",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "OpenCV Bootcamp",
    issuingBody: "OpenCV University",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Graphic Design",
    issuingBody: "DigiSkills.pk",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "WordPress",
    issuingBody: "DigiSkills.pk",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Freelancing",
    issuingBody: "DigiSkills.pk",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Social Media Marketing",
    issuingBody: "HP Life",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Business Email",
    issuingBody: "HP Life",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Strategic Planning",
    issuingBody: "HP Life",
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Professional Photography",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "cert-015",
    certificationName: "Prompt Engineering (Udemy)",
    issuingBody: null,
    certificationLevel: "Foundation",
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
]
