import { Employer } from "@/lib/types/employer"

export const sampleEmployers: Employer[] = [
  {
    id: "emp-001",
    name: "TechCorp Solutions",
    websiteUrl: "https://www.techcorp.com",
    linkedinUrl: "https://www.linkedin.com/company/techcorp-solutions",
    status: "Active",
    foundedYear: 2019,
    locations: [
      {
        id: "loc-emp-001-001",
        employerId: "emp-001",
        country: "United States",
        city: "New York",
        address: "123 Broadway, Manhattan, NY 10001",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 200,
        maxSize: 300,
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2023-01-15"),
      },
      {
        id: "loc-emp-001-002",
        employerId: "emp-001",
        country: "United Kingdom",
        city: "London",
        address: "45 Canary Wharf, London E14 5AB",
        isHeadquarters: false,
        salaryPolicy: "Tax Free",
        minSize: 80,
        maxSize: 120,
        createdAt: new Date("2023-03-20"),
        updatedAt: new Date("2023-03-20"),
      },
      {
        id: "loc-emp-001-003",
        employerId: "emp-001",
        country: "Singapore",
        city: "Singapore",
        address: "Marina Bay Financial Centre, 018956",
        isHeadquarters: false,
        salaryPolicy: "Remittance",
        minSize: 30,
        maxSize: 50,
        createdAt: new Date("2023-05-10"),
        updatedAt: new Date("2023-05-10"),
      },
      {
        id: "loc-emp-001-004",
        employerId: "emp-001",
        country: "Canada",
        city: "Toronto",
        address: "100 King Street West, Toronto ON M5X 1C7",
        isHeadquarters: false,
        salaryPolicy: "Standard",
        minSize: 60,
        maxSize: 100,
        createdAt: new Date("2023-07-25"),
        updatedAt: new Date("2023-07-25"),
      },
    ],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-07-25"),
  },
  {
    id: "emp-002",
    name: "Innovation Labs Inc",
    websiteUrl: "https://www.innovationlabs.com",
    linkedinUrl: "https://www.linkedin.com/company/innovation-labs-inc",
    status: "Active",
    foundedYear: 2015,
    locations: [
      {
        id: "loc-emp-002-001",
        employerId: "emp-002",
        country: "United States",
        city: "San Francisco",
        address: "1 Hacker Way, Menlo Park, CA 94025",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 150,
        maxSize: 200,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
      {
        id: "loc-emp-002-002",
        employerId: "emp-002",
        country: "Germany",
        city: "Berlin",
        address: "Unter den Linden 77, 10117 Berlin",
        isHeadquarters: false,
        salaryPolicy: "Tax Free",
        minSize: 40,
        maxSize: 80,
        createdAt: new Date("2023-06-15"),
        updatedAt: new Date("2023-06-15"),
      },
    ],
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2023-06-15"),
  },
  {
    id: "emp-003",
    name: "Digital Dynamics",
    websiteUrl: "https://www.digitaldynamics.com",
    linkedinUrl: "https://www.linkedin.com/company/digital-dynamics",
    status: "Active",
    foundedYear: 2020,
    locations: [
      {
        id: "loc-emp-003-001",
        employerId: "emp-003",
        country: "Australia",
        city: "Sydney",
        address: "Level 35, Governor Phillip Tower, 1 Farrer Place",
        isHeadquarters: true,
        salaryPolicy: "Remittance",
        minSize: 80,
        maxSize: 120,
        createdAt: new Date("2023-03-05"),
        updatedAt: new Date("2023-03-05"),
      },
      {
        id: "loc-emp-003-002",
        employerId: "emp-003",
        country: "Australia",
        city: "Melbourne",
        address: "Level 18, 567 Collins Street, Melbourne VIC 3000",
        isHeadquarters: false,
        salaryPolicy: "Standard",
        minSize: 25,
        maxSize: 40,
        createdAt: new Date("2023-08-12"),
        updatedAt: new Date("2023-08-12"),
      },
      {
        id: "loc-emp-003-003",
        employerId: "emp-003",
        country: "New Zealand",
        city: "Auckland",
        address: "Level 27, PWC Tower, 15 Customs Street West",
        isHeadquarters: false,
        salaryPolicy: "Remittance",
        minSize: 15,
        maxSize: 25,
        createdAt: new Date("2023-10-20"),
        updatedAt: new Date("2023-10-20"),
      },
    ],
    createdAt: new Date("2023-03-05"),
    updatedAt: new Date("2023-10-20"),
  },
  {
    id: "emp-004",
    name: "StartupX Technologies",
    websiteUrl: "https://www.startupx.tech",
    status: "Flagged",
    foundedYear: 2022,
    locations: [
      {
        id: "loc-emp-004-001",
        employerId: "emp-004",
        country: "United States",
        city: "Austin",
        address: "500 W 2nd St, Austin, TX 78701",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 8,
        maxSize: 12,
        createdAt: new Date("2023-04-18"),
        updatedAt: new Date("2023-04-18"),
      },
    ],
    createdAt: new Date("2023-04-18"),
    updatedAt: new Date("2023-04-18"),
  },
  {
    id: "emp-005",
    name: "Global Enterprise Corp",
    websiteUrl: "https://www.globalenterprise.com",
    linkedinUrl: "https://www.linkedin.com/company/global-enterprise",
    status: "Active",
    foundedYear: 2005,
    locations: [
      {
        id: "loc-emp-005-001",
        employerId: "emp-005",
        country: "United States",
        city: "Chicago",
        address: "233 S Wacker Dr, Chicago, IL 60606",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 400,
        maxSize: 600,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-emp-005-002",
        employerId: "emp-005",
        country: "Japan",
        city: "Tokyo",
        address: "1-1-1 Marunouchi, Chiyoda City, Tokyo 100-0005",
        isHeadquarters: false,
        salaryPolicy: "Tax Free",
        minSize: 100,
        maxSize: 150,
        createdAt: new Date("2023-03-15"),
        updatedAt: new Date("2023-03-15"),
      },
      {
        id: "loc-emp-005-003",
        employerId: "emp-005",
        country: "India",
        city: "Mumbai",
        address: "Nariman Point, Mumbai, Maharashtra 400021",
        isHeadquarters: false,
        salaryPolicy: "Remittance",
        minSize: 200,
        maxSize: 300,
        createdAt: new Date("2023-05-22"),
        updatedAt: new Date("2023-05-22"),
      },
      {
        id: "loc-emp-005-004",
        employerId: "emp-005",
        country: "United Kingdom",
        city: "Manchester",
        address: "1 Spinningfields, Manchester M3 3EB",
        isHeadquarters: false,
        salaryPolicy: "Standard",
        minSize: 50,
        maxSize: 80,
        createdAt: new Date("2023-09-08"),
        updatedAt: new Date("2023-09-08"),
      },
      {
        id: "loc-emp-005-005",
        employerId: "emp-005",
        country: "Brazil",
        city: "São Paulo",
        address: "Av. Paulista, 1578 - Bela Vista, São Paulo - SP",
        isHeadquarters: false,
        salaryPolicy: "Remittance",
        minSize: 80,
        maxSize: 120,
        createdAt: new Date("2023-11-12"),
        updatedAt: new Date("2023-11-12"),
      },
    ],
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-11-12"),
  },
  {
    id: "emp-006",
    name: "CloudTech Innovations",
    websiteUrl: "https://www.cloudtech.io",
    linkedinUrl: "https://www.linkedin.com/company/cloudtech-innovations",
    status: "Active",
    foundedYear: 2018,
    locations: [
      {
        id: "loc-emp-006-001",
        employerId: "emp-006",
        country: "Ireland",
        city: "Dublin",
        address: "Block 4, Harcourt Centre, Harcourt Road, Dublin 2",
        isHeadquarters: true,
        salaryPolicy: "Tax Free",
        minSize: 60,
        maxSize: 90,
        createdAt: new Date("2023-02-28"),
        updatedAt: new Date("2023-02-28"),
      },
      {
        id: "loc-emp-006-002",
        employerId: "emp-006",
        country: "Netherlands",
        city: "Amsterdam",
        address: "Vijzelstraat 68, 1017 HL Amsterdam",
        isHeadquarters: false,
        salaryPolicy: "Tax Free",
        minSize: 40,
        maxSize: 60,
        createdAt: new Date("2023-07-14"),
        updatedAt: new Date("2023-07-14"),
      },
    ],
    createdAt: new Date("2023-02-28"),
    updatedAt: new Date("2023-07-14"),
  },
  {
    id: "emp-007",
    name: "SecureBank Corporation",
    websiteUrl: "https://www.securebank.com",
    linkedinUrl: "https://www.linkedin.com/company/securebank-corp",
    status: "Active",
    foundedYear: 1985,
    locations: [
      {
        id: "loc-emp-007-001",
        employerId: "emp-007",
        country: "Switzerland",
        city: "Zurich",
        address: "Bahnhofstrasse 45, 8001 Zurich",
        isHeadquarters: true,
        salaryPolicy: "Tax Free",
        minSize: 300,
        maxSize: 400,
        createdAt: new Date("2023-01-10"),
        updatedAt: new Date("2023-01-10"),
      },
      {
        id: "loc-emp-007-002",
        employerId: "emp-007",
        country: "Luxembourg",
        city: "Luxembourg City",
        address: "2 Circuit de la Foire Internationale, 1347 Luxembourg",
        isHeadquarters: false,
        salaryPolicy: "Tax Free",
        minSize: 80,
        maxSize: 120,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
    ],
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2023-04-08"),
  },
  {
    id: "emp-008",
    name: "HealthTech Solutions",
    websiteUrl: "https://www.healthtech.com",
    status: "Active",
    foundedYear: 2021,
    locations: [
      {
        id: "loc-emp-008-001",
        employerId: "emp-008",
        country: "United States",
        city: "Boston",
        address: "1 Boston Medical Center Pl, Boston, MA 02118",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 120,
        maxSize: 180,
        createdAt: new Date("2023-05-15"),
        updatedAt: new Date("2023-05-15"),
      },
    ],
    createdAt: new Date("2023-05-15"),
    updatedAt: new Date("2023-05-15"),
  },
  {
    id: "emp-009",
    name: "EcoGreen Industries",
    websiteUrl: "https://www.ecogreen.com",
    linkedinUrl: "https://www.linkedin.com/company/ecogreen-industries",
    status: "Flagged",
    foundedYear: 2017,
    locations: [
      {
        id: "loc-emp-009-001",
        employerId: "emp-009",
        country: "Denmark",
        city: "Copenhagen",
        address: "Ørestads Boulevard 73, 2300 Copenhagen",
        isHeadquarters: true,
        salaryPolicy: "Tax Free",
        minSize: 100,
        maxSize: 150,
        createdAt: new Date("2023-06-22"),
        updatedAt: new Date("2023-06-22"),
      },
      {
        id: "loc-emp-009-002",
        employerId: "emp-009",
        country: "Sweden",
        city: "Stockholm",
        address: "Sveavägen 44, 111 34 Stockholm",
        isHeadquarters: false,
        salaryPolicy: "Standard",
        minSize: 60,
        maxSize: 90,
        createdAt: new Date("2023-09-18"),
        updatedAt: new Date("2023-09-18"),
      },
    ],
    createdAt: new Date("2023-06-22"),
    updatedAt: new Date("2023-09-18"),
  },
  {
    id: "emp-010",
    name: "AI Research Labs",
    websiteUrl: "https://www.airesearch.org",
    status: "Closed",
    foundedYear: 2023,
    locations: [
      {
        id: "loc-emp-010-001",
        employerId: "emp-010",
        country: "Canada",
        city: "Montreal",
        address: "1250 René-Lévesque Blvd W, Montreal, QC H3B 4W8",
        isHeadquarters: true,
        salaryPolicy: "Remittance",
        minSize: 15,
        maxSize: 15,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  }
]