import { Employer } from "@/lib/types/employer"

export const sampleEmployers: Employer[] = [
  {
    id: "emp-001",
    name: "DPL",
    websiteUrl: "https://www.dplit.com/",
    linkedinUrl: "https://pk.linkedin.com/company/dpl-it",
    status: "Active",
    foundedYear: 2003,
    ranking: "DPL Favourite",
    employerType: "Client Based",
    locations: [
      {
        id: "loc-emp-001-001",
        employerId: "emp-001",
        country: "Pakistan",
        city: "Islamabad",
        address: "I-8 Markaz",
        isHeadquarters: true,
        salaryPolicy: "Remittance",
        minSize: 100,
        maxSize: 150,
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2023-01-15"),
      },
      {
        id: "loc-emp-001-002",
        employerId: "emp-001",
        country: "Pakistan",
        city: "Karachi",
        address: null,
        isHeadquarters: false,
        salaryPolicy: "Remittance",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-03-20"),
        updatedAt: new Date("2023-03-20"),
      },
    ],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-07-25"),
  },
  {
    id: "emp-002",
    name: "United Sol",
    websiteUrl: "https://www.unitedsol.net/",
    linkedinUrl: "https://www.linkedin.com/company/unitedsol-pvt-ltd/",
    status: "Active",
    foundedYear: 2005,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-002-001",
        employerId: "emp-002",
        country: "Pakistan",
        city: "Islamabad",
        address: "Plot 349, Street 1, I-9/3",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 50,
        maxSize: 200,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
    ],
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2023-06-15"),
  },
  {
    id: "emp-003",
    name: "medequips",
    websiteUrl: "https://medequips.org/",
    linkedinUrl: "https://www.linkedin.com/company/medequips-smc/?originalSubdomain=pk",
    status: "Active",
    foundedYear: 1979,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-003-001",
        employerId: "emp-003",
        country: "Pakistan",
        city: "Lahore",
        address: "30- Shahrah-e-Quaid-e-Azam, Lahore, Punjab,54000",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 350,
        maxSize: 550,
        createdAt: new Date("2023-03-05"),
        updatedAt: new Date("2023-03-05"),
      },
    ],
    createdAt: new Date("2023-03-05"),
    updatedAt: new Date("2023-10-20"),
  },
  {
    id: "emp-004",
    name: "Radwi",
    websiteUrl: "http://www.rad-wi.com/",
    linkedinUrl: "https://www.linkedin.com/company/radwi/about/",
    status: "Active",
    foundedYear: 2021,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-004-001",
        employerId: "emp-004",
        country: "Pakistan",
        city: "Islamabad",
        address: "NSTP",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 55,
        createdAt: new Date("2023-04-18"),
        updatedAt: new Date("2023-04-18"),
      },
    ],
    createdAt: new Date("2023-04-18"),
    updatedAt: new Date("2023-04-18"),
  },
  {
    id: "emp-005",
    name: "Eziline Software House",
    websiteUrl: "http://eziline.com/",
    linkedinUrl: "https://www.linkedin.com/company/eziline/",
    status: "Active",
    foundedYear: 2007,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-005-001",
        employerId: "emp-005",
        country: "Pakistan",
        city: "Rawalpindi",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 50,
        maxSize: 200,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
    ],
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-11-12"),
  },
  {
    id: "emp-006",
    name: "Develo IT Solution",
    websiteUrl: "https://develoitsolutions.com/",
    linkedinUrl: "https://www.linkedin.com/company/develoitsolutions/about/",
    status: "Active",
    foundedYear: 2019,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-006-001",
        employerId: "emp-006",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 50,
        maxSize: 200,
        createdAt: new Date("2023-02-28"),
        updatedAt: new Date("2023-02-28"),
      },
    ],
    createdAt: new Date("2023-02-28"),
    updatedAt: new Date("2023-07-14"),
  },
  {
    id: "emp-007",
    name: "MYPro Appz",
    websiteUrl: "https://myproappz.com/",
    linkedinUrl: "https://www.linkedin.com/company/myproappz/about/",
    status: "Active",
    foundedYear: 2019,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-007-001",
        employerId: "emp-007",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-01-10"),
        updatedAt: new Date("2023-01-10"),
      },
    ],
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2023-04-08"),
  },
  {
    id: "emp-008",
    name: "Bellatrix Technology",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-008-001",
        employerId: "emp-008",
        country: "Pakistan",
        city: null,
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-05-15"),
        updatedAt: new Date("2023-05-15"),
      },
    ],
    createdAt: new Date("2023-05-15"),
    updatedAt: new Date("2023-05-15"),
  },
  {
    id: "emp-009",
    name: "Ninjas Code",
    websiteUrl: "https://www.ninjascode.com/",
    linkedinUrl: "https://www.linkedin.com/company/ninjas-code/about/",
    status: "Active",
    foundedYear: 2018,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-009-001",
        employerId: "emp-009",
        country: "United States",
        city: "California",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-06-22"),
        updatedAt: new Date("2023-06-22"),
      },
    ],
    createdAt: new Date("2023-06-22"),
    updatedAt: new Date("2023-09-18"),
  },
  {
    id: "emp-010",
    name: "Interactive Group",
    websiteUrl: null,
    linkedinUrl: "https://www.linkedin.com/company/interactive-group/",
    status: "Active",
    foundedYear: 1984,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-010-001",
        employerId: "emp-010",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 500,
        maxSize: 1000,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-011",
    name: "Electrosolz",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Closed",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-011-001",
        employerId: "emp-011",
        country: null,
        city: null,
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-012",
    name: "Fair Deal Marketing",
    websiteUrl: "https://fairdealmarketing.com/",
    linkedinUrl: "https://www.linkedin.com/company/fair-deal-marketing-pvt-ltd/",
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-012-001",
        employerId: "emp-012",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 500,
        maxSize: 1000,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-013",
    name: "Sukail",
    websiteUrl: "https://sukali.design/",
    linkedinUrl: "https://www.linkedin.com/company/sukalidesign/",
    status: "Active",
    foundedYear: 2019,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-013-001",
        employerId: "emp-013",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-014",
    name: "Viltco Technologies",
    websiteUrl: "https://viltco.com/",
    linkedinUrl: "https://www.linkedin.com/company/viltcosolution/about/",
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-014-001",
        employerId: "emp-014",
        country: "UAE",
        city: "Dubai",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-015",
    name: "Absoluit",
    websiteUrl: "https://absoluit.com/",
    linkedinUrl: "https://www.linkedin.com/company/absoluit/",
    status: "Active",
    foundedYear: 2016,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-015-001",
        employerId: "emp-015",
        country: "Norway",
        city: "Oslo",
        address: "Tvetenveien 152, Oppgang A, 0671 Oslo, Norway (Clutch)",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 100,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-016",
    name: "TheX Solution",
    websiteUrl: "https://thexsol.com/",
    linkedinUrl: null,
    status: "Active",
    foundedYear: 2017,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-016-001",
        employerId: "emp-016",
        country: "Pakistan",
        city: "Islamabad",
        address: "Arena Mall Plaza, 2nd Floor, Shop #32-33, Gulberg Green, Islamabad, Pakistan (thexsol.com)",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-017",
    name: "NinSol Technologies",
    websiteUrl: "https://www.ninesol.com",
    linkedinUrl: "https://www.linkedin.com/company/ninesol-technologies/",
    status: "Active",
    foundedYear: 2014,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-017-001",
        employerId: "emp-017",
        country: "Pakistan",
        city: "Islamabad",
        address: "First & Second Floor, 3-U Commercial Plaza, Sitara Market, G-7 Markaz, Islamabad, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 200,
        maxSize: 500,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-018",
    name: "Sementic Ltd",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-018-001",
        employerId: "emp-018",
        country: "Pakistan",
        city: null,
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-019",
    name: "Octaloop Technologies",
    websiteUrl: "https://www.octaloop.io/about-us",
    linkedinUrl: "https://www.linkedin.com/company/octaloop-itandns/about/",
    status: "Active",
    foundedYear: 2018,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-019-001",
        employerId: "emp-019",
        country: "Pakistan",
        city: "Islamabad",
        address: "Plot #31, Ground Floor, I-11/3 Sector, Islamabad 44000, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 51,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-020",
    name: "NESCOM",
    websiteUrl: "https://en.wikipedia.org/wiki/National_Engineering_%26_Scientific_Commission",
    linkedinUrl: null,
    status: "Active",
    foundedYear: 2000,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-020-001",
        employerId: "emp-020",
        country: "Pakistan",
        city: "Islamabad",
        address: "NESCOM Headquarters, Plot #94, Sector H-11/4, Islamabad, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 10000,
        maxSize: 16000,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-021",
    name: "AROK DEV",
    websiteUrl: null,
    linkedinUrl: "https://www.linkedin.com/company/arok-dev/",
    status: "Active",
    foundedYear: 2025,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-010-001",
        employerId: "emp-010",
        country: "Pakistan",
        city: "Remote",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-022",
    name: "Ufone & PTCL",
    websiteUrl: "https://ptcl.com.pk/Home/PageDetail?ItemId=332&linkId=883",
    linkedinUrl: "https://www.linkedin.com/company/ptcl-official/",
    status: "Active",
    foundedYear: 2001,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-022-001",
        employerId: "emp-022",
        country: "Pakistan",
        city: "Islamabad",
        address: "Ufone Tower, 55-C, Main Jinnah Avenue, F-7/1, Blue Area, Islamabad 44000, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 1000,
        maxSize: 5000,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
      {
        id: "loc-emp-022-002",
        employerId: "emp-022",
        country: "Pakistan",
        city: "Islamabad",
        address: "PTCL Headquarters, Block-E, Sector G-8/4, Islamabad-44000, Pakistan; registered office also at Ufone Tower, Plot #55-C, Main Jinnah Avenue, F-7/1, Blue Area, Islamabad.",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 14000,
        maxSize: 21000,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-023",
    name: "Hypersoft Inc",
    websiteUrl: "https://www.hypersoft.com.pk",
    linkedinUrl: "https://www.linkedin.com/company/hypersoftech/",
    status: "Active",
    foundedYear: 2020,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-023-001",
        employerId: "emp-023",
        country: "Pakistan",
        city: "Islamabad",
        address: "B3 Heights, 3rd Floor, Sector C, Phase 8, Bahria Town Business District, Rawalpindi, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 51,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-024",
    name: "The MicroZone",
    websiteUrl: "https://themicrozone.tech/",
    linkedinUrl: "https://www.linkedin.com/company/the-microzone/",
    status: "Active",
    foundedYear: 2021,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-024-001",
        employerId: "emp-024",
        country: "Pakistan",
        city: "Islamabad",
        address: "3rd Floor, ATS Plaza, Blue Area, Islamabad, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 51,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-025",
    name: "Askari Bank",
    websiteUrl: "https://askaribank.com/",
    linkedinUrl: "https://www.linkedin.com/company/askaribanklimited/",
    status: "Active",
    foundedYear: 1991,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-025-001",
        employerId: "emp-025",
        country: "Pakistan",
        city: "Islamabad",
        address: "Plot No. 18, NPT Building, F-8 Markaz, Islamabad, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 5000,
        maxSize: 10000,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-026",
    name: "Cybersoft Vantage (CSV)",
    websiteUrl: "https://www.cybersoftvantage.com/",
    linkedinUrl: "https://www.linkedin.com/company/csvantage/",
    status: "Active",
    foundedYear: 2019,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-026-001",
        employerId: "emp-026",
        country: "Pakistan",
        city: "Islamabad",
        address: "Plot 94-A, Street 07, Sector I-10/3, Islamabad 44000, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 51,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-027",
    name: "Strahlen Studios",
    websiteUrl: "https://www.strahlenstudios.com/",
    linkedinUrl: "https://www.linkedin.com/company/strahlen-studios/about/",
    status: "Active",
    foundedYear: 2013,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-027-001",
        employerId: "emp-027",
        country: "Pakistan",
        city: "Rawalpindi",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-028",
    name: "Servixer LLC",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-028-001",
        employerId: "emp-028",
        country: "Pakistan",
        city: null,
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-029",
    name: "Inexins Technologies",
    websiteUrl: "http://inexins.com/",
    linkedinUrl: "https://www.linkedin.com/company/inexins-technologies-pvt-ltd/",
    status: "Active",
    foundedYear: 2015,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-029-001",
        employerId: "emp-029",
        country: "Australia",
        city: null,
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-030",
    name: "Arpatech Pvt. Ltd",
    websiteUrl: "https://www.arpatech.com/?utm_source=chatgpt.com",
    linkedinUrl: "https://www.linkedin.com/company/arpatech/",
    status: "Active",
    foundedYear: 2003,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-030-001",
        employerId: "emp-030",
        country: "Pakistan",
        city: "Karachi",
        address: "Plot #195, Block A, SMCHS, Karachi, Sindh 75400, Pakistan (ArpaTech)",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 200,
        maxSize: 500,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-031",
    name: "Technology Ally Inc.",
    websiteUrl: "https://www.technologyally.com/?utm_source=chatgpt.com",
    linkedinUrl: "https://www.linkedin.com/company/technology-ally-inc-/about/",
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-031-001",
        employerId: "emp-031",
        country: "United States",
        city: "Overland Park",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 50,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-032",
    name: "XORD",
    websiteUrl: "https://xord.com/",
    linkedinUrl: "https://www.linkedin.com/company/xorddotcom/",
    status: "Active",
    foundedYear: 2018,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-032-001",
        employerId: "emp-032",
        country: "Pakistan",
        city: "Karachi",
        address: "191-Q, Block 2, PECHS, Karachi, Sindh 75400, Pakistan",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 100,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-033",
    name: "Afiniti",
    websiteUrl: "https://www.afiniti.com/",
    linkedinUrl: "https://www.linkedin.com/company/afiniti-com/",
    status: "Active",
    foundedYear: 2006,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-033-001",
        employerId: "emp-033",
        country: "Bermuda (legal HQ) / USA (operational) (Craft.co)",
        city: "Hamilton (Bermuda) official HQ; also Washington, DC USA office at 1701 Pennsylvania Ave NW Suite 600. (LegiStorm)",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 1,
        maxSize: 300,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-034",
    name: "TECKLOGICS",
    websiteUrl: "https://tecklogics.com.pk/",
    linkedinUrl: "https://www.linkedin.com/company/tecklogic/",
    status: "Active",
    foundedYear: 2015,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-034-001",
        employerId: "emp-034",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-035",
    name: "Cyber Reconnaissance & Combat",
    websiteUrl: "https://archive.bahria.edu.pk/oric/index.php/crc/",
    linkedinUrl: "https://www.linkedin.com/company/cyber-reconnaissance-and-combat-center/",
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-035-001",
        employerId: "emp-035",
        country: "Pakistan",
        city: "Islamabad",
        address: "Bahria university",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 30,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-036",
    name: "Launchify LLC",
    websiteUrl: "https://launchifyllc.com/",
    linkedinUrl: "https://www.linkedin.com/company/launchifyllc/about/",
    status: "Active",
    foundedYear: 2024,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-036-001",
        employerId: "emp-036",
        country: "United States",
        city: "Wyoming",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-037",
    name: "AICP",
    websiteUrl: null,
    linkedinUrl: "https://www.linkedin.com/company/aicommunitypakistan/about/",
    status: "Active",
    foundedYear: 2022,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-037-001",
        employerId: "emp-037",
        country: "Pakistan",
        city: "Lahore",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-038",
    name: "MarketMinds.pk",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-038-001",
        employerId: "emp-038",
        country: null,
        city: null,
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-039",
    name: "WRP (WeRplay)",
    websiteUrl: "https://www.werplay.com/",
    linkedinUrl: "https://www.linkedin.com/company/wrpstudios",
    status: "Active",
    foundedYear: 2010,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-039-001",
        employerId: "emp-039",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 200,
        maxSize: 500,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-040",
    name: "ASF Technologies Partners",
    websiteUrl: "https://asftechpartners.com/",
    linkedinUrl: "https://www.linkedin.com/company/asf-tech/",
    status: "Active",
    foundedYear: 2023,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-040-001",
        employerId: "emp-040",
        country: "District of Columbia",
        city: "Washington",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-041",
    name: "Ubiquify",
    websiteUrl: "http://www.ubiquifydigital.com/",
    linkedinUrl: "https://www.linkedin.com/company/ubiquify/",
    status: "Active",
    foundedYear: 2018,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-041-001",
        employerId: "emp-041",
        country: "United States",
        city: "Austin",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-042",
    name: "Qbatch",
    websiteUrl: "https://www.qbatch.com/",
    linkedinUrl: "https://www.linkedin.com/company/qbatch/",
    status: "Active",
    foundedYear: 2016,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-042-001",
        employerId: "emp-042",
        country: "United States",
        city: "Virginia",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 51,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-043",
    name: "Merik Solutions",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-043-001",
        employerId: "emp-043",
        country: "Pakistan",
        city: "Islamabad",
        address: "Plot 200 Street 1, I-10/3 I 10/3 I-10, Islamabad, 46000",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-044",
    name: "CanadaHitech",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Active",
    foundedYear: 2024,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-044-001",
        employerId: "emp-044",
        country: "United Arab Emirates",
        city: "Dubai",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-045",
    name: "Asian IT House",
    websiteUrl: "https://www.asianithouse.com/",
    linkedinUrl: "https://www.linkedin.com/company/asianithouse/",
    status: "Active",
    foundedYear: 2014,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-045-001",
        employerId: "emp-045",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 11,
        maxSize: 50,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-046",
    name: "Emumba Software House",
    websiteUrl: "https://www.emumba.com/%20(Emumba)",
    linkedinUrl: "https://www.linkedin.com/company/emumba/",
    status: "Active",
    foundedYear: 2011,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-046-001",
        employerId: "emp-046",
        country: "Pakistan",
        city: "Islamabad",
        address: "Plot #189-A, Korang Road, I-10/3, Islamabad, Pakistan. (CB Insights)",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-047",
    name: "Black Oaks Digital",
    websiteUrl: "https://itsblackoak.com/%20(Black%20Oak)",
    linkedinUrl: "https://www.linkedin.com/company/blackoakdigital/",
    status: "Active",
    foundedYear: 2021,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-047-001",
        employerId: "emp-047",
        country: "Pakistan",
        city: "Islamabad",
        address: "Office 404, 4th Floor, Hamdan Heights, Expressway, near Korang Interchange, Phase 5 Ghauri Town, Islamabad 44000. (Black Oak)",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 51,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-048",
    name: "Starland Marketing",
    websiteUrl: "http://starland.pk/%20(or%20variant)%20(Facebook)",
    linkedinUrl: "https://www.linkedin.com/company/star-land-marketing-private-limited/",
    status: "Active",
    foundedYear: 2010,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-048-001",
        employerId: "emp-048",
        country: "Pakistan",
        city: "Islamabad",
        address: "Street 07, Islamabad 44000, Pakistan. (SignalHire)",
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: 100,
        maxSize: 200,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-049",
    name: "Cameraholic",
    websiteUrl: null,
    linkedinUrl: "https://www.linkedin.com/in/mahir-lodhi-8697bb247",
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-049-001",
        employerId: "emp-049",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
  {
    id: "emp-050",
    name: "CUST Research Centre",
    websiteUrl: null,
    linkedinUrl: null,
    status: "Active",
    foundedYear: null,
    ranking: "Standard",
    employerType: "Product Based",
    locations: [
      {
        id: "loc-emp-050-001",
        employerId: "emp-050",
        country: "Pakistan",
        city: "Islamabad",
        address: null,
        isHeadquarters: true,
        salaryPolicy: "Standard",
        minSize: null,
        maxSize: null,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-01"),
      },
    ],
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2023-08-01"),
  },
]
