import { Project } from "@/lib/types/project"

export const sampleProjects: Project[] = [
  {
    id: "proj-001",
    projectName: "Miracle Morning Routine",
    employerName: "DPL",
    techStacks: ["react native", "express.js", "node.js", "aws", "sql", "nextjs", "react"],
    verticalDomains: ["Sports & Fitness", "Healthcare"],
    horizontalDomains: ["Mobile Application", "Workflow Automation", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Caching", "Logging & Monitoring", "CI/CD"],
    teamSize: "5",
    startDate: new Date("2023-06-01"),
    endDate: null, // Still in development
    status: "Development",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "proj-002", 
    projectName: "Pause Breathe Reflect",
    employerName: "DPL",
    techStacks: ["React Native", "Node.js", "AWS", "PostgreSQL"],
    verticalDomains: ["Healthcare", "Sports & Fitness"],
    horizontalDomains: ["Mobile Application", "Workflow Automation"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: new Date("2023-08-15"),
    endDate: null, // Still in development
    status: "Development",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-08-15"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "proj-003",
    projectName: "Parsley",
    employerName: "DPL",
    techStacks: ["react native", "node.js", "aws", "mysql"],
    verticalDomains: ["Retail & E-commerce", "Food Delivery"],
    horizontalDomains: ["Mobile Application", "E-commerce Platforms", "Supply Chain Management"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Queue Processing", "Caching", "Logging & Monitoring"],
    teamSize: "5",
    startDate: new Date("2020-01-01"),
    endDate: new Date("2021-01-01"),
    status: "Maintenance",
    description: "US based food delivery platform focused on home cooked food",
    notes: "the venture was shutdown by the owner due to idea not being kicked off.",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-03-25"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "proj-004",
    projectName: "Grocery App with PrestaShop",
    employerName: "United Sol",
    techStacks: ["PHP", "MySQL", "JavaScript", "PrestaShop"],
    verticalDomains: ["Retail & E-commerce"],
    horizontalDomains: ["E-commerce Platforms", "Supply Chain Management"],
    technicalAspects: ["REST APIs", "Query Optimization", "Caching", "Fault Tolerance"],
    teamSize: null,
    startDate: new Date("2022-03-01"),
    endDate: new Date("2022-09-30"),
    status: "Closed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-08-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "proj-005",
    projectName: "The Breath Source",
    employerName: "DPL",
    techStacks: ["react native", "node.js", "aws", "mysql", "nextjs"],
    verticalDomains: ["Healthcare", "Sports & Fitness"],
    horizontalDomains: ["Mobile Application", "Workflow Automation"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Background Jobs", "Caching", "Logging & Monitoring"],
    teamSize: "5",
    startDate: new Date("2024-10-01"),
    endDate: null, // Recently started, still in development
    status: "Development",
    description: "app that allows users to practice meditation, yoga and exercises.",
    notes: "currently in development phase, going well.",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-12-31"),
  },
  {
    id: "proj-006",
    projectName: "code check in bot",
    employerName: "DPL",
    techStacks: ["mern"],
    verticalDomains: ["Education"],
    horizontalDomains: ["DevOps & CI/CD", "Workflow Automation", "Business Intelligence & Analytics"],
    technicalAspects: ["CI/CD", "Background Jobs", "REST APIs", "Logging & Monitoring", "API Rate Limiting"],
    teamSize: "1",
    startDate: new Date("2023-09-15"),
    endDate: null, // Still in development
    status: "Development",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-09-15"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "proj-007",
    projectName: "iapartments",
    employerName: "DPL",
    techStacks: ["c/c++", "python", "micro controllers", "embedded systems", "hardware design", "firmware", "ASP.NET Core", "Angular", "AWS IoT", "aws"],
    verticalDomains: ["Real Estate", "Energy & Utilities"],
    horizontalDomains: ["IoT", "Cloud Computing"],
    technicalAspects: ["WebSockets", "Edge Computing", "Distributed Systems", "Fault Tolerance", "Logging & Monitoring", "Horizontal/vertical scaling"],
    teamSize: "30-35",
    startDate: new Date("2018-01-01"),
    endDate: null, // Long-term ongoing project
    status: "Development",
    description: "IOT enabled smart thermostat with connected devices",
    notes: "project is going successful",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "proj-008",
    projectName: "LMS App",
    employerName: "Eziline Software House",
    techStacks: ["Flutter", "Firebase"],
    verticalDomains: ["Education"],
    horizontalDomains: ["Document Management", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Caching", "Background Jobs", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2022-05-01"),
    endDate: new Date("2023-02-28"),
    status: "Maintenance",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-009",
    projectName: "Quran App",
    employerName: "Eziline Software House",
    techStacks: ["Flutter"],
    verticalDomains: ["Education", "Non-Profit & NGOs"],
    horizontalDomains: ["Mobile Application", "Document Management"],
    technicalAspects: ["REST APIs", "Caching", "Query Optimization"],
    teamSize: null,
    startDate: new Date("2022-03-15"),
    endDate: new Date("2022-11-30"),
    status: "Maintenance",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-010",
    projectName: "Chat App",
    employerName: "Eziline Software House",
    techStacks: ["Flutter", "Firebase"],
    verticalDomains: ["Telecommunications"],
    horizontalDomains: ["Communication & Collaboration"],
    technicalAspects: ["WebSockets", "REST APIs", "Real-time Communication", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2022-06-01"),
    endDate: new Date("2023-01-15"),
    status: "Maintenance",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-011",
    projectName: "Expense Tracker",
    employerName: null,
    techStacks: ["Java"],
    verticalDomains: ["Finance"],
    horizontalDomains: ["Business Intelligence & Analytics", "Workflow Automation"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Query Optimization", "Caching"],
    teamSize: null,
    startDate: new Date("2021-09-01"),
    endDate: new Date("2021-12-15"),
    status: "Closed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-012",
    projectName: "Food Recipe App",
    employerName: null,
    techStacks: ["Java"],
    verticalDomains: ["Retail & E-commerce", "Travel & Hospitality"],
    horizontalDomains: ["Mobile Application", "Document Management"],
    technicalAspects: ["REST APIs", "Caching", "Query Optimization"],
    teamSize: null,
    startDate: new Date("2021-08-01"),
    endDate: new Date("2021-11-30"),
    status: "Closed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-013",
    projectName: "The NTR - National Transfer Registry",
    employerName: null,
    techStacks: ["React Native", "TypeScript", "REST", "Real-time data"],
    verticalDomains: ["Healthcare", "Government & Public Services"],
    horizontalDomains: ["Document Management", "Workflow Automation"],
    technicalAspects: ["REST APIs", "WebSockets", "Real-time Communication", "Authentication/Authorization", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2024-02-01"),
    endDate: null, // In development
    status: "Development",
    description: "medical support app for hospital transfers",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-014",
    projectName: "Digital Quran App",
    employerName: null,
    techStacks: ["React Native", "TypeScript", "PDF SDK"],
    verticalDomains: ["Education", "Non-Profit & NGOs"],
    horizontalDomains: ["Mobile Application", "Document Management"],
    technicalAspects: ["REST APIs", "Caching", "Query Optimization", "Fault Tolerance"],
    teamSize: null,
    startDate: new Date("2024-03-15"),
    endDate: null, // In development
    status: "Development",
    description: null,
    notes: "PDF editing capability, corrections system",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-015",
    projectName: "Gradi - Discover New Food",
    employerName: null,
    techStacks: ["React Native", "TypeScript", "Firebase", "Stripe"],
    verticalDomains: ["Retail & E-commerce", "Travel & Hospitality"],
    horizontalDomains: ["E-commerce Platforms", "Mobile Application"],
    technicalAspects: ["REST APIs", "Payment Integration", "AI/ML integration", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2024-01-10"),
    endDate: null, // In development
    status: "Development",
    description: null,
    notes: "Food discovery platform w/ AI suggestions & Stripe",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-016",
    projectName: "Roadlee Rescuer",
    employerName: null,
    techStacks: ["React Native", "TypeScript", "Firebase", "Sockets", "Stripe"],
    verticalDomains: ["Automotive", "Travel & Hospitality"],
    horizontalDomains: ["Mobile Application", "Communication & Collaboration"],
    technicalAspects: ["WebSockets", "Real-time Communication", "Payment Integration", "Authentication/Authorization", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2023-11-01"),
    endDate: null, // In development
    status: "Development",
    description: null,
    notes: "On-demand emergency roadside assistance app",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-017",
    projectName: "Swyvery - Delivery App",
    employerName: null,
    techStacks: ["React Native", "TypeScript", "REST APIs"],
    verticalDomains: ["Retail & E-commerce", "Logistics & Supply chain"],
    horizontalDomains: ["E-commerce Platforms", "Supply Chain Management"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Queue Processing", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2023-10-01"),
    endDate: null, // In development
    status: "Development",
    description: null,
    notes: "Delivery app w/ tracking, payment integration",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-018",
    projectName: "AscendEd",
    employerName: "DPL",
    techStacks: ["React.js", "TypeScript", "Node.js + Express", "PostgreSQL", "AWS S3"],
    verticalDomains: ["Education"],
    horizontalDomains: ["ERP","Document Management", "Communication & Collaboration", "Business Intelligence & Analytics"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Background Jobs", "Caching", "Query Optimization", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2024-04-01"),
    endDate: null, // In development
    status: "Development",
    description: "Online course platform like Udemy; course enrollment, progress tracking, feedback",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-019",
    projectName: "GPS tracker",
    employerName: "Electrosolz",
    techStacks: ["STM32", "LoRa", "AWS IoT"],
    verticalDomains: ["Automotive", "Logistics & Supply chain"],
    horizontalDomains: ["IoT"],
    technicalAspects: ["Edge Computing", "Distributed Systems", "WebSockets", "Real-time Communication", "Fault Tolerance", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2019-06-01"),
    endDate: new Date("2020-03-31"),
    status: "Development",
    description: "A customized GPS tracker was made to track the Company's Delivery Trucks including optional features for Driver. Product was made using PIC32MX795 & Origin GPS.",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-020",
    projectName: "Water Management BMS",
    employerName: null,
    techStacks: ["STM32L4", "SX1276", "AWS IoT"],
    verticalDomains: ["Energy & Utilities", "Government & Public Services"],
    horizontalDomains: ["IoT", "Business Intelligence & Analytics"],
    technicalAspects: ["Edge Computing", "Distributed Systems", "WebSockets", "Real-time Communication", "Fault Tolerance", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2020-02-01"),
    endDate: new Date("2021-01-15"),
    status: "Development",
    description: "Building water control system",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-021",
    projectName: "B-IoT Dustbin Monitoring",
    employerName: null,
    techStacks: ["NRF9160", "LR1110"],
    verticalDomains: ["Government & Public Services", "Energy & Utilities"],
    horizontalDomains: ["IoT", "Business Intelligence & Analytics"],
    technicalAspects: ["Edge Computing", "Distributed Systems", "Real-time Communication", "Fault Tolerance", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2021-05-01"),
    endDate: new Date("2022-02-28"),
    status: "Development",
    description: "Detects bin fill level, real-time alerts",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-022",
    projectName: "Motion Simulator Ride",
    employerName: null,
    techStacks: ["ATmega328p", "NRF24L01"],
    verticalDomains: ["Media & Entertainment", "Sports & Fitness"],
    horizontalDomains: ["IoT"],
    technicalAspects: ["Edge Computing", "Real-time Communication", "Fault Tolerance"],
    teamSize: null,
    startDate: new Date("2020-08-01"),
    endDate: new Date("2021-03-31"),
    status: "Development",
    description: "AC Servo motors, 3DOF motion",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-023",
    projectName: "Autonomous Trade System",
    employerName: null,
    techStacks: ["Flutter", "Firebase"],
    verticalDomains: ["Finance", "Retail & E-commerce"],
    horizontalDomains: ["E-commerce Platforms", "Business Intelligence & Analytics"],
    technicalAspects: ["REST APIs", "AI/ML integration", "Queue Processing", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2023-04-01"),
    endDate: null, // In development
    status: "Development",
    description: "Online platform connecting vendors",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-024",
    projectName: "Wearables - multiple",
    employerName: null,
    techStacks: ["FPGA", "Bluetooth", "Sensors"],
    verticalDomains: ["Healthcare", "Sports & Fitness"],
    horizontalDomains: ["IoT"],
    technicalAspects: ["Edge Computing", "Real-time Communication", "Fault Tolerance", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2019-09-01"),
    endDate: new Date("2020-12-31"),
    status: "Development",
    description: "IoT based medical & measurement devices",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-025",
    projectName: "Promote Master",
    employerName: null,
    techStacks: ["Flutter", "Bloc", "Firebase", "REST APIs"],
    verticalDomains: ["Retail & E-commerce", "Media & Entertainment"],
    horizontalDomains: ["Mobile Application", "Business Intelligence & Analytics"],
    technicalAspects: ["REST APIs", "WebSockets", "Authentication/Authorization", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: new Date("2023-02-01"),
    endDate: new Date("2023-08-31"),
    status: "Development",  
    description: "Frontend (Flutter) + Backend (Java Spring Boot + SQL Server) + FCM + Socket.IO",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-026",
    projectName: "Cabsoluit",
    employerName: null,
    techStacks: ["Kotlin", "MVVM", "Bluetooth", "Stripe"],
    verticalDomains: ["Travel & Hospitality", "Automotive"],
    horizontalDomains: ["Mobile Application", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "Payment Integration", "Real-time Communication", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2023-03-15"),
    endDate: new Date("2023-10-30"),
    status: "Development",
    description: "Taxi app features & integrations for Norway market",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-027",
    projectName: "Vibranta Connect",
    employerName: null,
    techStacks: ["Flutter", "Kotlin"],
    verticalDomains: ["Telecommunications"],
    horizontalDomains: ["Mobile Application", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2023-05-01"),
    endDate: new Date("2023-11-15"),
    status: "Development",
    description: "eSIM & package provider solution",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-028",
    projectName: "EzyShifa",
    employerName: null,
    techStacks: ["WebRTC", "Kotlin", "Doctor booking"],
    verticalDomains: ["Healthcare"],
    horizontalDomains: ["Mobile Application", "Communication & Collaboration", "Workflow Automation"],
    technicalAspects: ["WebRTC", "Real-time Communication", "REST APIs", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2023-01-10"),
    endDate: new Date("2023-07-31"),
    status: "Development",
    description: "Medical field app",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-029",
    projectName: "Upswing Learning",
    employerName: null,
    techStacks: ["Kotlin", "OpenCV", "SignalR", "WebView"],
    verticalDomains: ["Education"],
    horizontalDomains: ["Mobile Application", "Document Management", "Business Intelligence & Analytics"],
    technicalAspects: ["WebSockets", "AI/ML integration", "Real-time Communication", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2022-09-01"),
    endDate: new Date("2023-03-31"),
    status: "Development",
    description: "Educational testing platform",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-030",
    projectName: "Upswing Attendance",
    employerName: null,
    techStacks: ["Kotlin", "SQL", "SignalR", "OpenCV"],
    verticalDomains: ["Education", "HR & Recruitment"],
    horizontalDomains: ["HRM", "Business Intelligence & Analytics"],
    technicalAspects: ["WebSockets", "AI/ML integration", "Real-time Communication", "Authentication/Authorization", "Query Optimization"],
    teamSize: null,
    startDate: new Date("2022-10-01"),
    endDate: new Date("2023-04-15"),
    status: "Development",
    description: "Attendance system with face detection",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-031",
    projectName: "Legal Document Summarization",
    employerName: null,
    techStacks: ["Flask", "MongoDB", "NLP", "LLaMA API"],
    verticalDomains: ["Legal"],
    horizontalDomains: ["AI & Machine Learning", "Document Management"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Background Jobs", "Query Optimization", "Caching"],
    teamSize: null,
    startDate: new Date("2024-01-15"),
    endDate: null, // In development
    status: "Development",
    description: "Transformer model w/ RAG chatbot",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-032",
    projectName: "Weapon Detection System",
    employerName: null,
    techStacks: ["YOLO v5-v10", "OpenCV", "PyTorch"],
    verticalDomains: ["Government & Public Services", "Security"],
    horizontalDomains: ["AI & Machine Learning", "Cybersecurity"],
    technicalAspects: ["AI/ML integration", "Real-time Processing", "Edge Computing", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2024-05-01"),
    endDate: null, // In development
    status: "Development",
    description: "Real-time YOLO detection via Streamlit",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-033",
    projectName: "Image Editing App",
    employerName: null,
    techStacks: ["Python", "Tkinter", "OpenCV"],
    verticalDomains: ["Media & Entertainment"],
    horizontalDomains: ["Document Management"],
    technicalAspects: ["AI/ML integration", "Image Processing", "Caching"],
    teamSize: null,
    startDate: new Date("2023-06-01"),
    endDate: new Date("2023-09-30"),
    status: "Development",
    description: "Tkinter-based photo editing desktop app",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-034",
    projectName: "Recipe Generator",
    employerName: null,
    techStacks: ["Streamlit", "NLP", "HuggingFace"],
    verticalDomains: ["Retail & E-commerce", "Travel & Hospitality"],
    horizontalDomains: ["AI & Machine Learning"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: new Date("2023-07-15"),
    endDate: new Date("2023-10-31"),
    status: "Development",
    description: "FLAN-T5 based AI recipe generator",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-035",
    projectName: "Restaurant Ratings Predictor",
    employerName: null,
    techStacks: ["Flask", "JS", "RF & LR models"],
    verticalDomains: ["Retail & E-commerce", "Travel & Hospitality"],
    horizontalDomains: ["AI & Machine Learning", "Business Intelligence & Analytics"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Query Optimization", "Caching"],
    teamSize: null,
    startDate: new Date("2023-08-01"),
    endDate: new Date("2023-11-15"),
    status: "Development",
    description: "ML model for rating predictions",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-036",
    projectName: "Chatbot",
    employerName: null,
    techStacks: ["Python", "NLP", "TensorFlow"],
    verticalDomains: ["Telecommunications"],
    horizontalDomains: ["AI & Machine Learning", "Communication & Collaboration"],
    technicalAspects: ["AI/ML integration", "WebSockets", "Real-time Communication", "REST APIs", "Caching"],
    teamSize: null,
    startDate: new Date("2022-11-01"),
    endDate: new Date("2023-02-28"),
    status: "Development",
    description: "QA testing, user flow validation",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-037",
    projectName: "Status Saver",
    employerName: null,
    techStacks: ["Android", "Java", "SQLite"],
    verticalDomains: ["Telecommunications"],
    horizontalDomains: ["Mobile Application", "Document Management"],
    technicalAspects: ["REST APIs", "Caching", "Query Optimization"],
    teamSize: null,
    startDate: new Date("2022-09-01"),
    endDate: new Date("2023-01-31"),
    status: "Development",
    description: "Compatibility and usability testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-038",
    projectName: "Screen Mirroring",
    employerName: null,
    techStacks: ["WebRTC", "Node.js", "Socket.io"],
    verticalDomains: ["Telecommunications", "Media & Entertainment"],
    horizontalDomains: ["Communication & Collaboration"],
    technicalAspects: ["WebRTC", "WebSockets", "Real-time Communication", "Authentication/Authorization"],
    teamSize: null,
    startDate: new Date("2022-10-15"),
    endDate: new Date("2023-03-15"),
    status: "Development",
    description: "QA testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-039",
    projectName: "PDF Reader",
    employerName: null,
    techStacks: ["React", "PDF.js", "JavaScript"],
    verticalDomains: ["Education", "Legal"],
    horizontalDomains: ["Document Management"],
    technicalAspects: ["REST APIs", "Caching", "Query Optimization"],
    teamSize: null,
    startDate: new Date("2022-08-01"),
    endDate: new Date("2022-12-31"),
    status: "Development",
    description: "Functionality & testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-040",
    projectName: "AGORZ Delivery",
    employerName: null,
    techStacks: ["React Native", "Node.js", "MongoDB"],
    verticalDomains: ["Retail & E-commerce", "Logistics & Supply chain"],
    horizontalDomains: ["E-commerce Platforms", "Supply Chain Management"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Queue Processing", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2023-01-15"),
    endDate: new Date("2023-06-30"),
    status: "Development",
    description: "Web and mobile QA",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-041",
    projectName: "Language Translator",
    employerName: null,
    techStacks: ["Python", "NLP", "TensorFlow"],
    verticalDomains: ["Education", "Telecommunications"],
    horizontalDomains: ["AI & Machine Learning", "Communication & Collaboration"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Caching", "Background Jobs"],
    teamSize: null,
    startDate: new Date("2022-07-01"),
    endDate: new Date("2022-11-30"),
    status: "Development",
    description: "Postman & Logcat-based debugging",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-042",
    projectName: "File Manager",
    employerName: null,
    techStacks: ["Android", "Java", "SQLite"],
    verticalDomains: ["Government & Public Services"],
    horizontalDomains: ["Document Management"],
    technicalAspects: ["REST APIs", "Caching", "Query Optimization", "Authentication/Authorization"],
    teamSize: null,
    startDate: new Date("2022-05-01"),
    endDate: new Date("2022-09-30"),
    status: "Maintenance",
    description: "Functional & performance testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-043",
    projectName: "Object Remover",
    employerName: null,
    techStacks: ["Python", "OpenCV", "Deep Learning"],
    verticalDomains: ["Media & Entertainment"],
    horizontalDomains: ["AI & Machine Learning"],
    technicalAspects: ["AI/ML integration", "Image Processing", "REST APIs", "Background Jobs"],
    teamSize: null,
    startDate: new Date("2022-04-01"),
    endDate: new Date("2022-08-31"),
    status: "Maintenance",
    description: "Testing & integration",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-044",
    projectName: "Music Generator",
    employerName: null,
    techStacks: ["Python", "TensorFlow", "MIDI"],
    verticalDomains: ["Media & Entertainment"],
    horizontalDomains: ["AI & Machine Learning"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: new Date("2022-03-01"),
    endDate: new Date("2022-07-31"),
    status: "Maintenance",
    description: "API & AI model testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-045",
    projectName: "IA Photo Enhancer",
    employerName: null,
    techStacks: ["Python", "OpenCV", "Deep Learning"],
    verticalDomains: ["Media & Entertainment"],
    horizontalDomains: ["AI & Machine Learning"],
    technicalAspects: ["AI/ML integration", "Image Processing", "REST APIs", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: new Date("2022-02-01"),
    endDate: new Date("2022-06-30"),
    status: "Maintenance",
    description: "AI model QA work",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-046",
    projectName: "COVID SOP Violation Detection (FYP)",
    employerName: null,
    techStacks: ["Tensorflow", "PyTorch", "CUDA"],
    verticalDomains: ["Healthcare", "Government & Public Services"],
    horizontalDomains: ["AI & Machine Learning", "Cybersecurity"],
    technicalAspects: ["AI/ML integration", "Real-time Processing", "Edge Computing", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2020-09-01"),
    endDate: new Date("2021-06-30"),
    status: "Maintenance",
    description: "Real-time ML-based SOP monitoring",
    notes: null,
    projectLink: null,
    projectType: "Academic",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-047",
    projectName: "COVID Tracker App",
    employerName: null,
    techStacks: [".NET Core", "API consumption"],
    verticalDomains: ["Healthcare", "Government & Public Services"],
    horizontalDomains: ["Mobile Application", "Business Intelligence & Analytics"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2020-04-01"),
    endDate: new Date("2020-08-31"),
    status: "Maintenance",
    description: "Desktop application for COVID stats",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-048",
    projectName: "Streaming App (Freelance)",
    employerName: null,
    techStacks: [".NET Core APIs", "EF Core", "MySQL", "AWS S3", "Stripe"],
    verticalDomains: ["Media & Entertainment"],
    horizontalDomains: ["Cloud Computing", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "Payment Integration", "Authentication/Authorization", "Caching", "Load Balancing", "Horizontal/vertical scaling"],
    teamSize: null,
    startDate: new Date("2021-02-01"),
    endDate: new Date("2021-10-31"),
    status: "Maintenance",
    description: "Video streaming platform",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-049",
    projectName: "UTZ-RA Project",
    employerName: null,
    techStacks: ["Java", "Spring Boot", "MySQL"],
    verticalDomains: ["Agriculture"],
    horizontalDomains: ["Document Management", "Workflow Automation"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Query Optimization", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2021-05-01"),
    endDate: new Date("2021-12-31"),
    status: "Maintenance",
    description: "Sustainable farming label software - manual testing & client interaction",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-050",
    projectName: "License Renewal Connections",
    employerName: null,
    techStacks: ["Selenium", "Cucumber", "Jenkins"],
    verticalDomains: ["Government & Public Services"],
    horizontalDomains: ["DevOps & CI/CD", "Workflow Automation"],
    technicalAspects: ["CI/CD", "Automation", "Background Jobs", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2021-07-01"),
    endDate: new Date("2021-11-30"),
    status: "Closed",
    description: "Automated using Selenium + Cucumber BDD + Jenkins CI/CD",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-051",
    projectName: "Phoenix DAO / Tipply Tank",
    employerName: null,
    techStacks: ["Blockchain", "Solidity", "Web3"],
    verticalDomains: ["Finance"],
    horizontalDomains: ["Blockchain", "Business Intelligence & Analytics"],
    technicalAspects: ["Distributed Systems", "Authentication/Authorization", "Fault Tolerance", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2022-01-15"),
    endDate: null, // Ongoing
    status: "Development",
    description: "Blockchain projects (scrum environment)",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-052",
    projectName: "HRQoL (pet health assessment)",
    employerName: null,
    techStacks: ["React Native", "Node.js", "MongoDB"],
    verticalDomains: ["Healthcare"],
    horizontalDomains: ["Mobile Application", "Business Intelligence & Analytics"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Caching", "Query Optimization", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2022-03-01"),
    endDate: new Date("2022-08-31"),
    status: "Development",
    description: "Mobile app testing - UI + functional + performance",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-053",
    projectName: "INET ED (education platform)",
    employerName: null,
    techStacks: ["React", "Node.js", "PostgreSQL"],
    verticalDomains: ["Education"],
    horizontalDomains: ["Document Management", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Caching", "Background Jobs", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2021-09-01"),
    endDate: new Date("2022-02-28"),
    status: "Closed",
    description: "Regression & sanity testing on live system",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-054",
    projectName: "EnrollSource",
    employerName: null,
    techStacks: ["React", "Node.js", "PostgreSQL"],
    verticalDomains: ["Healthcare", "Insurance"],
    horizontalDomains: ["CRM", "Workflow Automation"],
    technicalAspects: ["REST APIs", "Authentication/Authorization", "Multi-Tenancy", "Query Optimization", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2021-03-01"),
    endDate: new Date("2021-08-31"),
    status: "Closed",
    description: "QA lead — CRM for medical quotes, health insurance",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-055",
    projectName: "Afiniti ACT",
    employerName: null,
    techStacks: ["Python", "Machine Learning", "APIs"],
    verticalDomains: ["Telecommunications"],
    horizontalDomains: ["AI & Machine Learning", "Business Intelligence & Analytics"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Queue Processing", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2020-06-01"),
    endDate: new Date("2020-12-31"),
    status: "Closed",
    description: "AI routing software for call centers - black-box testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-056",
    projectName: "Agent Megavaya",
    employerName: null,
    techStacks: ["Java", "Spring Boot", "MySQL"],
    verticalDomains: ["Telecommunications"],
    horizontalDomains: ["CRM", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "WebSockets", "Real-time Communication", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2020-08-01"),
    endDate: new Date("2021-01-31"),
    status: "Closed",
    description: "Tested for call flow defects",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-057",
    projectName: "Mobile App Testing (Multiple)",
    employerName: null,
    techStacks: ["Selenium", "Appium", "JUnit"],
    verticalDomains: ["Telecommunications"],
    horizontalDomains: ["DevOps & CI/CD", "Mobile Application"],
    technicalAspects: ["CI/CD", "Automation", "Logging & Monitoring", "Fault Tolerance"],
    teamSize: null,
    startDate: new Date("2020-01-01"),
    endDate: new Date("2020-12-31"),
    status: "Closed",
    description: "Experience with Android/iOS real-time QA tasks",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-058",
    projectName: "PIXIE - AI Assistant Robot",
    employerName: null,
    techStacks: ["TensorFlow", "PyTorch", "YOLO", "OpenCV", "Arduino"],
    verticalDomains: ["Education", "Healthcare"],
    horizontalDomains: ["AI & Machine Learning", "IoT"],
    technicalAspects: ["AI/ML integration", "Edge Computing", "Real-time Processing", "Fault Tolerance", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2019-09-01"),
    endDate: new Date("2020-05-31"),
    status: "Closed",
    description: "Voice-controlled AI robot with facial recognition & navigation; won 1st place at COMSATS Expo 2025",
    notes: null,
    projectLink: null,
    projectType: "Academic",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-059",
    projectName: "Virtual Dentist Analyzer",
    employerName: null,
    techStacks: ["CNN", "Keras", "OpenCV"],
    verticalDomains: ["Healthcare"],
    horizontalDomains: ["AI & Machine Learning"],
    technicalAspects: ["AI/ML integration", "Image Processing", "REST APIs", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: new Date("2020-01-15"),
    endDate: new Date("2020-06-30"),
    status: "Closed",
    description: "AI tool for dental X-ray analysis to detect cavities and anomalies",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-060",
    projectName: "LifeAid Chatbot",
    employerName: null,
    techStacks: ["Rasa", "Transformers", "Python", "NLP"],
    verticalDomains: ["Healthcare"],
    horizontalDomains: ["AI & Machine Learning", "Communication & Collaboration"],
    technicalAspects: ["AI/ML integration", "WebSockets", "Real-time Communication", "REST APIs", "Caching"],
    teamSize: null,
    startDate: new Date("2020-07-01"),
    endDate: new Date("2020-11-30"),
    status: "Closed",
    description: "Conversational AI for emergency medical guidance via voice/text",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-061",
    projectName: "Smart Real Estate Price Predictor",
    employerName: null,
    techStacks: ["Scikit-learn", "XGBoost", "Flask"],
    verticalDomains: ["Real Estate", "Finance"],
    horizontalDomains: ["AI & Machine Learning", "Business Intelligence & Analytics"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Query Optimization", "Caching"],
    teamSize: null,
    startDate: new Date("2021-01-01"),
    endDate: new Date("2021-05-31"),
    status: "Closed",
    description: "Predicts property prices using local market data",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-062",
    projectName: "Advanced Face & Gesture Recognition",
    employerName: null,
    techStacks: ["YOLOv5", "OpenCV", "PyTorch"],
    verticalDomains: ["Government & Public Services", "Security"],
    horizontalDomains: ["AI & Machine Learning", "Cybersecurity"],
    technicalAspects: ["AI/ML integration", "Real-time Processing", "Edge Computing", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2021-06-01"),
    endDate: new Date("2021-10-31"),
    status: "Closed",
    description: "Real-time surveillance and recognition system",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-063",
    projectName: "LingoTranslator NLP Tool",
    employerName: null,
    techStacks: ["HuggingFace", "BERT", "NLTK"],
    verticalDomains: ["Education", "Telecommunications"],
    horizontalDomains: ["AI & Machine Learning", "Communication & Collaboration"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: new Date("2021-11-01"),
    endDate: new Date("2022-03-31"),
    status: "Closed",
    description: "Multilingual translation with semantic understanding",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-064",
    projectName: "AI Virtual Classroom System",
    employerName: null,
    techStacks: ["TensorFlow", "Computer Vision"],
    verticalDomains: ["Education"],
    horizontalDomains: ["AI & Machine Learning", "Communication & Collaboration"],
    technicalAspects: ["AI/ML integration", "WebSockets", "Real-time Communication", "Authentication/Authorization", "Caching"],
    teamSize: null,
    startDate: new Date("2022-04-01"),
    endDate: new Date("2022-08-31"),
    status: "Closed",
    description: "AI for grading, attendance & engagement monitoring",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-065",
    projectName: "Digit Recognition System",
    employerName: null,
    techStacks: ["CNN", "Keras"],
    verticalDomains: ["Education"],
    horizontalDomains: ["AI & Machine Learning", "Mobile Application"],
    technicalAspects: ["AI/ML integration", "Real-time Processing", "Edge Computing", "Caching"],
    teamSize: null,
    startDate: new Date("2019-11-01"),
    endDate: new Date("2020-02-28"),
    status: "Closed",
    description: "Real-time MNIST digit recognition mobile app",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-066",
    projectName: "Life Safety Emergency App",
    employerName: null,
    techStacks: ["Flutter", "Firebase", "Google Maps API"],
    verticalDomains: ["Healthcare", "Government & Public Services"],
    horizontalDomains: ["Mobile Application", "Communication & Collaboration"],
    technicalAspects: ["REST APIs", "Real-time Communication", "Authentication/Authorization", "Caching", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2020-03-01"),
    endDate: new Date("2020-07-31"),
    status: "Closed",
    description: "SOS alerts with GPS tracking & emergency assistance",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-067",
    projectName: "Pixel Pal Browser Extension",
    employerName: null,
    techStacks: ["JavaScript", "Chrome API"],
    verticalDomains: ["Media & Entertainment"],
    horizontalDomains: ["Mobile Application"],
    technicalAspects: ["REST APIs", "Caching", "Background Jobs"],
    teamSize: null,
    startDate: new Date("2019-05-01"),
    endDate: new Date("2019-08-31"),
    status: "Closed",
    description: "Gamified digital pet inside browser interface",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-068",
    projectName: "Student Management System",
    employerName: null,
    techStacks: ["Python", "MySQL", "Tkinter"],
    verticalDomains: ["Education"],
    horizontalDomains: ["HRM", "Document Management"],
    technicalAspects: ["REST APIs", "Query Optimization", "Caching", "Authentication/Authorization"],
    teamSize: null,
    startDate: new Date("2019-09-01"),
    endDate: new Date("2019-12-31"),
    status: "Closed",
    description: "Academic desktop app for student record management",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-069",
    projectName: "Intelligent Object Detector",
    employerName: null,
    techStacks: ["YOLOv5", "OpenCV"],
    verticalDomains: ["Government & Public Services", "Security"],
    horizontalDomains: ["AI & Machine Learning", "Cybersecurity"],
    technicalAspects: ["AI/ML integration", "Real-time Processing", "Edge Computing", "Logging & Monitoring"],
    teamSize: null,
    startDate: new Date("2020-09-01"),
    endDate: new Date("2021-01-31"),
    status: "Closed",
    description: "YOLO-based object detection system",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-070",
    projectName: "Sentiment Analysis Bot",
    employerName: null,
    techStacks: ["Python", "NLTK"],
    verticalDomains: ["Retail & E-commerce", "Media & Entertainment"],
    horizontalDomains: ["AI & Machine Learning", "Business Intelligence & Analytics"],
    technicalAspects: ["AI/ML integration", "REST APIs", "Background Jobs", "Caching"],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Closed",
    description: "Detects emotional sentiment from user text",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },

]