import { Project } from "@/lib/types/project"

export const sampleProjects: Project[] = [
  {
    id: "proj-001",
    projectName: "E-Commerce Platform Redesign",
    employerName: "TechCorp Solutions",
    techStacks: ["React", "Node.js", "PostgreSQL", "AWS", "TypeScript", "Redux"],
    verticalDomains: ["E-Commerce", "Retail"],
    horizontalDomains: ["CRM", "Payment Gateway", "Inventory Management"],
    technicalAspects: ["Microservices", "Authorization", "Real-time Updates", "API Integration"],
    teamSize: "12",
    startDate: new Date("2023-06-15"),
    endDate: new Date("2024-02-28"),
    status: "Active",
    description: "Complete redesign and modernization of legacy e-commerce platform. The project involves migrating from monolithic architecture to microservices, implementing modern React frontend with TypeScript, and building scalable backend services. Key features include real-time inventory updates, advanced search capabilities, personalized recommendations, and seamless payment integration.",
    notes: "Client specifically requested mobile-first approach. Need to ensure 99.9% uptime during migration. Weekly demos scheduled every Friday.",
    projectLink: "https://ecommerce.techcorp.com",
    projectType: "Academic",
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "proj-002", 
    projectName: "Healthcare Management System",
    employerName: "MediTech Innovations",
    techStacks: ["Angular", "ASP.NET Core", "SQL Server", "Azure", "C#"],
    verticalDomains: ["Healthcare", "Medical"],
    horizontalDomains: ["ERP", "Patient Management", "Billing"],
    technicalAspects: ["HIPAA Compliance", "Authorization", "Data Encryption", "Audit Logging"],
    teamSize: "8",
    startDate: new Date("2023-09-01"),
    endDate: new Date("2024-06-30"),
    status: "Active",
    description: "Development of comprehensive healthcare management system for hospitals and clinics. The system includes patient records management, appointment scheduling, billing integration, and compliance reporting. Built with strict HIPAA compliance requirements and robust security measures.",
    notes: "Critical security review required before each release. Integration with existing legacy systems must be seamless.",
    projectLink: "https://healthsys.meditech.com",
    projectType: "Employer",
    createdAt: new Date("2023-08-15"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "proj-003",
    projectName: "Financial Trading Dashboard",
    employerName: "FinanceFirst Corp",
    techStacks: ["React", "Python", "FastAPI", "WebSocket", "Redis", "Docker"],
    verticalDomains: ["Finance", "Trading", "Investment"],
    horizontalDomains: ["Analytics", "Real-time Data", "Portfolio Management"],
    technicalAspects: ["Real-time Updates", "Data Analytics", "Microservices", "Caching"],
    teamSize: "15",
    startDate: new Date("2023-04-10"),
    endDate: undefined, // Ongoing
    status: "Active",
    description: "Real-time financial trading dashboard with advanced analytics and portfolio management capabilities. Features include live market data streams, customizable charts, risk assessment tools, and automated trading alerts. Built for high-frequency trading environments with sub-millisecond response times.",
    notes: "Performance is critical - latency must be under 10ms. Extensive testing with market data simulators required.",
    projectLink: "https://trading.financefirst.com",
    projectType: "Employer",
    createdAt: new Date("2023-03-25"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "proj-004",
    projectName: "Educational Platform",
    employerName: "EduTech Solutions",
    techStacks: ["Next.js", "MongoDB", "Node.js", "Socket.io", "Tailwind CSS"],
    verticalDomains: ["Education", "E-Learning"],
    horizontalDomains: ["LMS", "Content Management", "Assessment"],
    technicalAspects: ["Real-time Collaboration", "Video Streaming", "Content Delivery"],
    teamSize: "6",
    startDate: new Date("2023-08-20"),
    endDate: new Date("2024-04-15"),
    status: "Active",
    description: "Modern educational platform with interactive learning modules, real-time collaboration tools, and comprehensive assessment capabilities. Includes video conferencing, whiteboard sharing, assignment management, and progress tracking for students and instructors.",
    notes: "Focus on accessibility compliance (WCAG 2.1 AA). Mobile responsiveness is crucial for student engagement.",
    projectLink: "https://learn.edutech.com",
    projectType: "Employer",
    createdAt: new Date("2023-08-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "proj-005",
    projectName: "Supply Chain Optimization",
    employerName: "LogiCorp Industries",
    techStacks: ["Vue.js", "Java", "Spring Boot", "MySQL", "Kubernetes", "Grafana"],
    verticalDomains: ["Logistics", "Supply Chain"],
    horizontalDomains: ["ERP", "Inventory Management", "Analytics"],
    technicalAspects: ["Microservices", "Data Analytics", "Monitoring", "API Integration"],
    teamSize: "20-25",
    startDate: new Date("2023-01-15"),
    endDate: new Date("2023-12-31"),
    status: "Completed",
    description: "End-to-end supply chain optimization platform with predictive analytics, real-time tracking, and automated inventory management. System processes over 1 million transactions daily and provides insights for cost reduction and efficiency improvements.",
    notes: "Successfully reduced client's operational costs by 23%. System now handles 3x the original transaction volume.",
    projectType: "Freelance",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-12-31"),
  },
  {
    id: "proj-006",
    projectName: "AI-Powered Analytics Engine",
    employerName: "DataInsight Labs",
    techStacks: ["Python", "TensorFlow", "React", "PostgreSQL", "Docker", "Airflow"],
    verticalDomains: ["AI/ML", "Data Science", "Analytics"],
    horizontalDomains: ["Business Intelligence", "Predictive Analytics"],
    technicalAspects: ["Machine Learning", "Data Pipeline", "Microservices", "Caching"],
    teamSize: "10",
    startDate: new Date("2023-10-01"),
    endDate: new Date("2024-08-31"),
    status: "Active",
    description: "Advanced analytics engine powered by machine learning algorithms for business intelligence and predictive analytics. Processes large datasets to provide actionable insights, trend predictions, and automated recommendations for business decision-making.",
    notes: "Model accuracy must exceed 85%. Requires integration with client's existing data warehouse infrastructure.",
    projectType: "Freelance",
    createdAt: new Date("2023-09-15"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "proj-007",
    projectName: "Mobile Banking Application",
    employerName: "SecureBank Corp",
    techStacks: ["React Native", "Node.js", "MongoDB", "JWT", "Biometric Auth"],
    verticalDomains: ["Banking", "FinTech"],
    horizontalDomains: ["Mobile App", "Security", "Payment Processing"],
    technicalAspects: ["Authorization", "Encryption", "Biometric Authentication", "API Security"],
    teamSize: "18",
    startDate: new Date("2023-03-01"),
    endDate: new Date("2024-01-15"),
    status: "Completed",
    description: "Secure mobile banking application with biometric authentication, real-time transaction processing, and advanced security features. Supports multiple payment methods, money transfers, bill payments, and comprehensive account management functionality.",
    notes: "Passed all security audits and regulatory compliance checks. App store ratings: 4.8/5 stars with 50K+ downloads in first month.",
    projectLink: "https://apps.securebank.com/mobile",
    projectType: "Freelance",
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "proj-008",
    projectName: "IoT Device Management Platform",
    employerName: "SmartTech Industries",
    techStacks: ["Angular", "Java", "Spring Boot", "InfluxDB", "MQTT", "Docker"],
    verticalDomains: ["IoT", "Manufacturing", "Smart City"],
    horizontalDomains: ["Device Management", "Data Collection", "Monitoring"],
    technicalAspects: ["IoT Protocols", "Real-time Data", "Microservices", "Edge Computing"],
    teamSize: "14",
    startDate: new Date("2023-07-01"),
    endDate: undefined,
    status: "Active",
    description: "Comprehensive IoT device management platform for industrial and smart city applications. Handles device provisioning, firmware updates, data collection, and real-time monitoring. Supports thousands of connected devices with low-latency communication protocols.",
    notes: "Must handle 10K+ concurrent device connections. Edge computing integration planned for Q2 2024.",
    projectLink: "https://iot.smarttech.com",
    projectType: "Freelance",
    createdAt: new Date("2023-06-20"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-009",
    projectName: "Content Management System",
    employerName: "Media Solutions Inc",
    techStacks: ["MERN", "GraphQL", "AWS S3", "Elasticsearch", "Redis"],
    verticalDomains: ["Media", "Publishing", "Content"],
    horizontalDomains: ["CMS", "Content Delivery", "Search"],
    technicalAspects: ["Content Delivery", "Search Optimization", "Caching", "CDN"],
    teamSize: "7",
    startDate: new Date("2023-11-01"),
    endDate: new Date("2024-05-31"),
    status: "Planning",
    description: "Modern content management system with advanced publishing workflows, multi-media support, and global content delivery. Features include collaborative editing, version control, automated SEO optimization, and intelligent content recommendations.",
    notes: "Client requires 99.99% uptime SLA. Content delivery must be optimized for global audience with CDN integration.",
    projectLink: "https://cms.mediasolutions.com",
    projectType: "Employer",
    createdAt: new Date("2023-10-20"),
    updatedAt: new Date("2023-12-15"),
  },
  {
    id: "proj-010",
    projectName: "Blockchain Voting System",
    employerName: "GovTech Innovations",
    techStacks: ["Solidity", "React", "Web3.js", "IPFS", "Node.js", "Ethereum"],
    verticalDomains: ["Government", "Blockchain", "Security"],
    horizontalDomains: ["Voting System", "Identity Verification", "Audit"],
    technicalAspects: ["Blockchain", "Smart Contracts", "Encryption", "Decentralization"],
    teamSize: "9",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-12-31"),
    status: "Planning",
    description: "Secure blockchain-based voting system for government elections with tamper-proof record keeping, voter anonymity, and transparent audit trails. Implements smart contracts for vote validation and uses decentralized storage for immutable record keeping.",
    notes: "Extremely high security requirements. Must pass government security audits. Pilot testing with local municipalities planned.",
    projectType: "Personal",
    createdAt: new Date("2023-12-10"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "proj-011",
    projectName: "Legacy System Migration",
    employerName: "Enterprise Corp",
    techStacks: ["Java", "Spring Boot", "Angular", "Oracle", "Microservices", "Kubernetes"],
    verticalDomains: ["Enterprise", "Legacy Modernization"],
    horizontalDomains: ["ERP", "Data Migration", "System Integration"],
    technicalAspects: ["Data Migration", "Legacy Integration", "Microservices", "API Gateway"],
    teamSize: "25-30",
    startDate: new Date("2023-05-01"),
    endDate: new Date("2024-03-31"),
    status: "On Hold",
    description: "Large-scale migration of legacy mainframe systems to modern cloud-based architecture. Involves data migration, API development, user interface modernization, and gradual system cutover to minimize business disruption.",
    notes: "Project temporarily paused due to budget allocation review. Expected to resume Q2 2024. Critical business systems dependency requires careful planning.",
    projectType: "Employer",
    createdAt: new Date("2023-04-15"),
    updatedAt: new Date("2023-11-30"),
  },
  {
    id: "proj-012",
    projectName: "Real-time Chat Application",
    employerName: "ConnectTech Startup",
    techStacks: ["React", "Socket.io", "Node.js", "MongoDB", "WebRTC", "Docker"],
    verticalDomains: ["Communication", "Social Media"],
    horizontalDomains: ["Messaging", "Video Calling", "File Sharing"],
    technicalAspects: ["Real-time Communication", "WebRTC", "Message Encryption", "Scalability"],
    teamSize: "5",
    startDate: new Date("2023-12-01"),
    endDate: new Date("2024-04-30"),
    status: "Active",
    description: "Modern real-time chat application with video calling, file sharing, and group collaboration features. Supports end-to-end encryption, message history, and seamless cross-platform synchronization for web and mobile users.",
    notes: "Targeting 100K+ concurrent users. Performance optimization is ongoing. Beta launch planned for March 2024.",
    projectLink: "https://chat.connecttech.com",
    projectType: "Employer",
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date("2024-01-14"),
  }
]
