import { Project } from "@/lib/types/project"

export const sampleProjects: Project[] = [
  {
    id: "proj-001",
    projectName: "Miracle Morning Routine",
    employerName: "DPL",
    techStacks: ["react native", "express.js", "node.js", "aws", "sql", "nextjs", "react"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: "5",
    startDate: null,
    endDate: null,
    status: "Active",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "proj-002", 
    projectName: "Pause Breathe Reflect",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-08-15"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "proj-003",
    projectName: "Parsley",
    employerName: "DPL",
    techStacks: ["react native", "node.js", "aws", "mysql"],
    verticalDomains: ["food delivery platform"],
    horizontalDomains: ["mobile application"],
    technicalAspects: ["monolethic"],
    teamSize: "5",
    startDate: new Date("2020-01-01"),
    endDate: new Date("2021-01-01"),
    status: "Completed",
    description: "US based food delivery platform focused on home cooked food",
    notes: "the venture was shutdown by the owner due to idea not being kicked off.",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-03-25"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "proj-004",
    projectName: "Grocery App with PrestaShop",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Completed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-08-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "proj-005",
    projectName: "The Breath Source",
    employerName: "DPL",
    techStacks: ["react native", "node.js", "aws", "mysql", "nextjs"],
    verticalDomains: ["meditation"],
    horizontalDomains: ["mobile application"],
    technicalAspects: [],
    teamSize: "5",
    startDate: new Date("2025-01-01"),
    endDate: null,
    status: "Active",
    description: "app that allows users to practice meditation, yoga and exercises.",
    notes: "currently in development phase, going well.",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-12-31"),
  },
  {
    id: "proj-006",
    projectName: "code check in bot",
    employerName: "DPL",
    techStacks: ["mern"],
    verticalDomains: [],
    horizontalDomains: ["evaluation software"],
    technicalAspects: ["tool calling"],
    teamSize: "1",
    startDate: null,
    endDate: null,
    status: "Active",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-09-15"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "proj-007",
    projectName: "iapartments",
    employerName: "DPL",
    techStacks: ["c/c++", "python", "micro controllers", "embedded systems", "hardware design", "firmware"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: "30-35",
    startDate: new Date("2018-01-01"),
    endDate: null,
    status: "Active",
    description: "IOT enabled smart thermostat with connected devices",
    notes: "project is going successful",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "proj-008",
    projectName: "LMS App",
    employerName: "DPL",
    techStacks: ["Flutter", "Firebase"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Completed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-009",
    projectName: "Quran App",
    employerName: "DPL",
    techStacks: ["Flutter"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Completed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-010",
    projectName: "Chat App",
    employerName: "DPL",
    techStacks: ["Flutter", "Firebase"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Completed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-011",
    projectName: "Expense Tracker",
    employerName: "DPL",
    techStacks: ["Java"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Completed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-012",
    projectName: "Food Recipe App",
    employerName: "DPL",
    techStacks: ["Java"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Completed",
    description: null,
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-013",
    projectName: "The NTR – National Transfer Registry",
    employerName: "DPL",
    techStacks: ["React Native", "TypeScript", "REST", "Real-time data"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "medical support app for hospital transfers",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-014",
    projectName: "Digital Quran App",
    employerName: "DPL",
    techStacks: ["React Native", "TypeScript", "PDF SDK"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: null,
    notes: "PDF editing capability, corrections system",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-015",
    projectName: "Gradi – Discover New Food",
    employerName: "DPL",
    techStacks: ["React Native", "TypeScript", "Firebase", "Stripe"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: null,
    notes: "Food discovery platform w/ AI suggestions & Stripe",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-016",
    projectName: "Roadlee Rescuer",
    employerName: "DPL",
    techStacks: ["React Native", "TypeScript", "Firebase", "Sockets", "Stripe"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: null,
    notes: "On-demand emergency roadside assistance app",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-017",
    projectName: "Swyvery – Delivery App",
    employerName: "DPL",
    techStacks: ["React Native", "TypeScript", "REST APIs"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: null,
    notes: "Delivery app w/ tracking, payment integration",
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-018",
    projectName: "AscendEd",
    employerName: "DPL",
    techStacks: ["React.js", "TypeScript", "Node.js + Express", "PostgreSQL", "AWS S3"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Online course platform like Udemy; course enrollment, progress tracking, feedback",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-019",
    projectName: "GPS tracker",
    employerName: "DPL",
    techStacks: ["STM32", "LoRa", "AWS IoT"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "A customized GPS tracker was made to track the Company's Delivery Trucks including optional features for Driver. Product was made using PIC32MX795 & Origin GPS.",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-020",
    projectName: "Water Management BMS",
    employerName: "DPL",
    techStacks: ["STM32L4", "SX1276", "AWS IoT"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Building water control system",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-021",
    projectName: "B-IoT Dustbin Monitoring",
    employerName: "DPL",
    techStacks: ["NRF9160", "LR1110"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Detects bin fill level, real-time alerts",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-022",
    projectName: "Motion Simulator Ride",
    employerName: "DPL",
    techStacks: ["ATmega328p", "NRF24L01"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "AC Servo motors, 3DOF motion",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-023",
    projectName: "Autonomous Trade System",
    employerName: "DPL",
    techStacks: ["Flutter", "Firebase"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Online platform connecting vendors",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-024",
    projectName: "Wearables – multiple",
    employerName: "DPL",
    techStacks: ["FPGA", "Bluetooth", "Sensors"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "IoT based medical & measurement devices",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-025",
    projectName: "Promote Master",
    employerName: "DPL",
    techStacks: ["Flutter", "Bloc", "Firebase", "REST APIs"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Frontend (Flutter) + Backend (Java Spring Boot + SQL Server) + FCM + Socket.IO",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-026",
    projectName: "Cabsoluit",
    employerName: "DPL",
    techStacks: ["Kotlin", "MVVM", "Bluetooth", "Stripe"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Taxi app features & integrations for Norway market",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-027",
    projectName: "Vibranta Connect",
    employerName: "DPL",
    techStacks: ["Flutter", "Kotlin"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "eSIM & package provider solution",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-028",
    projectName: "EzyShifa",
    employerName: "DPL",
    techStacks: ["WebRTC", "Kotlin", "Doctor booking"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Medical field app",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-029",
    projectName: "Upswing Learning",
    employerName: "DPL",
    techStacks: ["Kotlin", "OpenCV", "SignalR", "WebView"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Educational testing platform",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-030",
    projectName: "Upswing Attendance",
    employerName: "DPL",
    techStacks: ["Kotlin", "SQL", "SignalR", "OpenCV"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Attendance system with face detection",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-031",
    projectName: "Legal Document Summarization",
    employerName: "DPL",
    techStacks: ["Flask", "MongoDB", "NLP", "LLaMA API"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Transformer model w/ RAG chatbot",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-032",
    projectName: "Weapon Detection System",
    employerName: "DPL",
    techStacks: ["YOLO v5-v10", "OpenCV", "PyTorch"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Real-time YOLO detection via Streamlit",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-033",
    projectName: "Image Editing App",
    employerName: "DPL",
    techStacks: ["Python", "Tkinter", "OpenCV"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Tkinter-based photo editing desktop app",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-034",
    projectName: "Recipe Generator",
    employerName: "DPL",
    techStacks: ["Streamlit", "NLP", "HuggingFace"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "FLAN-T5 based AI recipe generator",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-035",
    projectName: "Restaurant Ratings Predictor",
    employerName: "DPL",
    techStacks: ["Flask", "JS", "RF & LR models"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "ML model for rating predictions",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-036",
    projectName: "Chatbot",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "QA testing, user flow validation",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-037",
    projectName: "Status Saver",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Compatibility and usability testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-038",
    projectName: "Screen Mirroring",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "QA testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-039",
    projectName: "PDF Reader",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Functionality & testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-040",
    projectName: "AGORZ Delivery",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Web and mobile QA",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-041",
    projectName: "Language Translator",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Postman & Logcat-based debugging",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-042",
    projectName: "File Manager",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Functional & performance testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-043",
    projectName: "Object Remover",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Testing & integration",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-044",
    projectName: "Music Generator",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "API & AI model testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-045",
    projectName: "IA Photo Enhancer",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "AI model QA work",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-046",
    projectName: "COVID SOP Violation Detection (FYP)",
    employerName: "DPL",
    techStacks: ["Tensorflow", "PyTorch", "CUDA"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Real-time ML-based SOP monitoring",
    notes: null,
    projectLink: null,
    projectType: "Academic",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-047",
    projectName: "COVID Tracker App",
    employerName: "DPL",
    techStacks: [".NET Core", "API consumption"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Desktop application for COVID stats",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-048",
    projectName: "Streaming App (Freelance)",
    employerName: "DPL",
    techStacks: [".NET Core APIs", "EF Core", "MySQL", "AWS S3", "Stripe"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Video streaming platform",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-049",
    projectName: "UTZ-RA Project",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Sustainable farming label software – manual testing & client interaction",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-050",
    projectName: "License Renewal Connections",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Automated using Selenium + Cucumber BDD + Jenkins CI/CD",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-051",
    projectName: "Phoenix DAO / Tipply Tank",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Blockchain projects (scrum environment)",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-052",
    projectName: "HRQoL (pet health assessment)",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Mobile app testing – UI + functional + performance",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-053",
    projectName: "INET ED (education platform)",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Regression & sanity testing on live system",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-054",
    projectName: "EnrollSource",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "QA lead — CRM for medical quotes, health insurance",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-055",
    projectName: "Afiniti ACT",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "AI routing software for call centers – black-box testing",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-056",
    projectName: "Agent Megavaya",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Tested for call flow defects",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-057",
    projectName: "Mobile App Testing (Multiple)",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Experience with Android/iOS real-time QA tasks",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-058",
    projectName: "PIXIE – AI Assistant Robot",
    employerName: "DPL",
    techStacks: ["TensorFlow", "PyTorch", "YOLO", "OpenCV", "Arduino"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Voice-controlled AI robot with facial recognition & navigation; won 1st place at COMSATS Expo 2025",
    notes: null,
    projectLink: null,
    projectType: "Academic",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-059",
    projectName: "Virtual Dentist Analyzer",
    employerName: "DPL",
    techStacks: ["CNN", "Keras", "OpenCV"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "AI tool for dental X-ray analysis to detect cavities and anomalies",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-060",
    projectName: "LifeAid Chatbot",
    employerName: "DPL",
    techStacks: ["Rasa", "Transformers", "Python", "NLP"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Conversational AI for emergency medical guidance via voice/text",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-061",
    projectName: "Smart Real Estate Price Predictor",
    employerName: "DPL",
    techStacks: ["Scikit-learn", "XGBoost", "Flask"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Predicts property prices using local market data",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-062",
    projectName: "Advanced Face & Gesture Recognition",
    employerName: "DPL",
    techStacks: ["YOLOv5", "OpenCV", "PyTorch"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Real-time surveillance and recognition system",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-063",
    projectName: "LingoTranslator NLP Tool",
    employerName: "DPL",
    techStacks: ["HuggingFace", "BERT", "NLTK"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Multilingual translation with semantic understanding",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-064",
    projectName: "AI Virtual Classroom System",
    employerName: "DPL",
    techStacks: ["TensorFlow", "Computer Vision"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "AI for grading, attendance & engagement monitoring",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-065",
    projectName: "Digit Recognition System",
    employerName: "DPL",
    techStacks: ["CNN", "Keras"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Real-time MNIST digit recognition mobile app",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-066",
    projectName: "Life Safety Emergency App",
    employerName: "DPL",
    techStacks: ["Flutter", "Firebase", "Google Maps API"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "SOS alerts with GPS tracking & emergency assistance",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-067",
    projectName: "Pixel Pal Browser Extension",
    employerName: "DPL",
    techStacks: ["JavaScript", "Chrome API"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Gamified digital pet inside browser interface",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-068",
    projectName: "Student Management System",
    employerName: "DPL",
    techStacks: ["Python", "MySQL", "Tkinter"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Academic desktop app for student record management",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-069",
    projectName: "Intelligent Object Detector",
    employerName: "DPL",
    techStacks: ["YOLOv5", "OpenCV"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "YOLO-based object detection system",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-070",
    projectName: "Sentiment Analysis Bot",
    employerName: "DPL",
    techStacks: ["Python", "NLTK"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Detects emotional sentiment from user text",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-071",
    projectName: "E-commerce Platform",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Performed functional, usability & performance testing for luxury e-commerce app",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-072",
    projectName: "Game Testing",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Tested multiple games – quality checks, training sessions for internal teams",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-073",
    projectName: "Payment & Order Testing",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Validated payment processing & order management accuracy",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-074",
    projectName: "Regression & Compatibility Testing",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Tested across platforms & devices to ensure consistency",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-075",
    projectName: "Data Quality Checks",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Identified mismatches & performance bottlenecks",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-076",
    projectName: "CarFlex",
    employerName: "DPL",
    techStacks: ["React Native", "Firebase", "GPT-3.5", "Three.js", "Tailwind", "Nodemailer"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "React Native app + web version with 3D models & email system",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-077",
    projectName: "Twitter UI Clone",
    employerName: "DPL",
    techStacks: ["Vite", "Tailwind CSS", "Google Icons"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Fully responsive frontend replica of Twitter",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-078",
    projectName: "Spotify Clone",
    employerName: "DPL",
    techStacks: ["HTML", "CSS", "JavaScript"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Dynamic clone with playlists from JSON",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-079",
    projectName: "Responsive Todo App",
    employerName: "DPL",
    techStacks: ["Vite", "React", "Tailwind CSS"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Local storage + animated UI",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-080",
    projectName: "Pizza Shop Management System",
    employerName: "DPL",
    techStacks: ["C++ / DSA Concepts"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Order + feedback management with DSA",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-081",
    projectName: "Gulshanabad Society Management System",
    employerName: "DPL",
    techStacks: ["Java (OOP)"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "OOP-based property management",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-082",
    projectName: "Restaurant Management System",
    employerName: "DPL",
    techStacks: ["Java"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Automated restaurant operations",
    notes: null,
    projectLink: null,
    projectType: "Personal",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-083",
    projectName: "EcomCircles (Lead)",
    employerName: "DPL",
    techStacks: ["MERN Stack", "Stripe", "Microservices"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "E-commerce platform for drop-shippers: product listing, repricing, warehouse integration, Stripe subscription plans",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-084",
    projectName: "AutoOrdering (Lead)",
    employerName: "DPL",
    techStacks: ["JavaScript", "APIs", "Automation", "Integrations"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Real-time automation bot for order fulfillment & subscription management",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-085",
    projectName: "Gateless (Lead)",
    employerName: "DPL",
    techStacks: ["React", "CI/CD", "Docker", "Kubernetes"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Music platform for artists, CI/CD pipelines reducing deployment time by 40%",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-086",
    projectName: "EII (Contributor)",
    employerName: "DPL",
    techStacks: ["Video Processing", "AI Model Integration"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Video AI analysis—emotion/sentiment extraction with real-time visualization & AI model",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-087",
    projectName: "Page Optimizer (Contributor)",
    employerName: "DPL",
    techStacks: ["React", "Analytics", "Web Scraping"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "SEO optimization tool for rankings, keywords, scheduling alerts",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-088",
    projectName: "Bev360 (Contributor)",
    employerName: "DPL",
    techStacks: ["React", "OIDC Auth", "MERN Backend"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Beverage lifecycle management—buying, making, shipping alcohol products",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-089",
    projectName: "Easy Ride",
    employerName: "DPL",
    techStacks: ["ASP.NET Core", "Angular", "SQL Server", "Stripe", "Azure"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Ride-sharing platform with real-time tracking, Stripe payments & JWT auth",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-090",
    projectName: "Smart Indus City",
    employerName: "DPL",
    techStacks: ["ASP.NET Core", "Angular", "Azure", "SQL Server"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Smart city management – traffic monitoring & civic services",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-091",
    projectName: "Tap&Go",
    employerName: "DPL",
    techStacks: ["ASP.NET Core (C#)", "SQL Server"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Transportation app like Careem/Uber",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-092",
    projectName: "Bizfolio",
    employerName: "DPL",
    techStacks: ["ASP.NET Core", "Angular 12", "Azure", "SQL Server"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Cloud-based document signing & workflow automation",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-093",
    projectName: "Dynaos",
    employerName: "DPL",
    techStacks: ["ASP.NET Core", "SQL Server"],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Healthcare web app for patient record & analytics",
    notes: null,
    projectLink: null,
    projectType: "Employer",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-094",
    projectName: "Foodpanda",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Production / Editing",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-095",
    projectName: "Savour Foods",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Videographer",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-096",
    projectName: "Fazalerabbi Jewellers",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Visual production",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-097",
    projectName: "Rana Petstore",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Photography / marketing",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-098",
    projectName: "Punjab Cash & Carry",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Promo shooting",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-099",
    projectName: "Hanif Medical Complex",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Video production",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-100",
    projectName: "Discover Pakistan",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Video editor",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-101",
    projectName: "DG ISPR",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Media project",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-102",
    projectName: "PRM Associates",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Production",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-103",
    projectName: "Bill Solutions",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Video content",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "proj-104",
    projectName: "Lodhi Autos",
    employerName: "DPL",
    techStacks: [],
    verticalDomains: [],
    horizontalDomains: [],
    technicalAspects: [],
    teamSize: null,
    startDate: null,
    endDate: null,
    status: "Active",
    description: "Marketing visuals",
    notes: null,
    projectLink: null,
    projectType: "Freelance",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-01-18"),
  },
]
