import { University } from "@/lib/types/university"

export const sampleUniversities: University[] = [
  {
    id: "uni-001",
    name: "Massachusetts Institute of Technology",
    country: "United States",
    ranking: "Top",
    websiteUrl: "https://www.mit.edu",
    linkedinUrl: "https://www.linkedin.com/school/mit",
    locations: [
      {
        id: "loc-001-001",
        universityId: "uni-001",
        city: "Cambridge",
        address: "77 Massachusetts Avenue, Cambridge, MA 02139",
        isMainCampus: true,
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2023-01-15"),
      },
      {
        id: "loc-001-002", 
        universityId: "uni-001",
        city: "Boston",
        address: "Kendall Square Campus, 292 Main Street, Cambridge, MA 02142",
        isMainCampus: false,
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2023-01-15"),
      },
      {
        id: "loc-001-003",
        universityId: "uni-001",
        city: "Lincoln",
        address: "Lincoln Laboratory, 244 Wood Street, Lexington, MA 02421",
        isMainCampus: false,
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2023-01-15"),
      },
    ],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-01-15"),
  },
  {
    id: "uni-002",
    name: "Stanford University",
    country: "United States",
    ranking: "Top",
    websiteUrl: "https://www.stanford.edu",
    linkedinUrl: "https://www.linkedin.com/school/stanford-university",
    locations: [
      {
        id: "loc-002-001",
        universityId: "uni-002",
        city: "Stanford",
        address: "450 Jane Stanford Way, Stanford, CA 94305",
        isMainCampus: true,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
      {
        id: "loc-002-002",
        universityId: "uni-002",
        city: "Redwood City",
        address: "Stanford Research Park, 1501 Page Mill Road, Palo Alto, CA 94304",
        isMainCampus: false,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
    ],
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2023-02-10"),
  },
  {
    id: "uni-003",
    name: "Harvard University",
    country: "United States",
    ranking: "Top",
    websiteUrl: "https://www.harvard.edu",
    linkedinUrl: "https://www.linkedin.com/school/harvard-university",
    locations: [
      {
        id: "loc-003-001",
        universityId: "uni-003",
        city: "Cambridge",
        address: "Massachusetts Hall, Cambridge, MA 02138",
        isMainCampus: true,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-002",
        universityId: "uni-003",
        city: "Boston",
        address: "Harvard Medical School, 25 Shattuck Street, Boston, MA 02115",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-003",
        universityId: "uni-003",
        city: "Allston",
        address: "Harvard Business School, Soldiers Field, Boston, MA 02163",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
    ],
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "uni-004",
    name: "University of Cambridge",
    country: "United Kingdom",
    ranking: "Top",
    websiteUrl: "https://www.cam.ac.uk",
    linkedinUrl: "https://www.linkedin.com/school/university-of-cambridge",
    locations: [
      {
        id: "loc-004-001",
        universityId: "uni-004",
        city: "Cambridge",
        address: "The Old Schools, Trinity Lane, Cambridge CB2 1TN",
        isMainCampus: true,
        createdAt: new Date("2023-03-05"),
        updatedAt: new Date("2023-03-05"),
      },
    ],
    createdAt: new Date("2023-03-05"),
    updatedAt: new Date("2023-03-05"),
  },
  {
    id: "uni-005",
    name: "University of Oxford",
    country: "United Kingdom",
    ranking: "Top",
    websiteUrl: "https://www.ox.ac.uk",
    linkedinUrl: "https://www.linkedin.com/school/university-of-oxford",
    locations: [
      {
        id: "loc-005-001",
        universityId: "uni-005",
        city: "Oxford",
        address: "University Offices, Wellington Square, Oxford OX1 2JD",
        isMainCampus: true,
        createdAt: new Date("2023-02-28"),
        updatedAt: new Date("2023-02-28"),
      },
    ],
    createdAt: new Date("2023-02-28"),
    updatedAt: new Date("2023-02-28"),
  },
  {
    id: "uni-006",
    name: "California Institute of Technology",
    country: "United States",
    ranking: "Top",
    websiteUrl: "https://www.caltech.edu",
    linkedinUrl: "https://www.linkedin.com/school/california-institute-of-technology",
    locations: [
      {
        id: "loc-006-001",
        universityId: "uni-006",
        city: "Pasadena",
        address: "1200 East California Boulevard, Pasadena, CA 91125",
        isMainCampus: true,
        createdAt: new Date("2023-03-12"),
        updatedAt: new Date("2023-03-12"),
      },
    ],
    createdAt: new Date("2023-03-12"),
    updatedAt: new Date("2023-03-12"),
  },
  {
    id: "uni-007",
    name: "ETH Zurich",
    country: "Switzerland",
    ranking: "Top",
    websiteUrl: "https://ethz.ch",
    linkedinUrl: "https://www.linkedin.com/school/eth-zurich",
    locations: [
      {
        id: "loc-007-001",
        universityId: "uni-007",
        city: "Zurich",
        address: "Rämistrasse 101, 8092 Zurich",
        isMainCampus: true,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
    ],
    createdAt: new Date("2023-04-08"),
    updatedAt: new Date("2023-04-08"),
  },
  {
    id: "uni-008",
    name: "University of Toronto",
    country: "Canada",
    ranking: "Top",
    websiteUrl: "https://www.utoronto.ca",
    linkedinUrl: "https://www.linkedin.com/school/university-of-toronto",
    locations: [
      {
        id: "loc-008-001",
        universityId: "uni-008",
        city: "Toronto",
        address: "27 King's College Circle, Toronto, ON M5S 1A1",
        isMainCampus: true,
        createdAt: new Date("2023-03-22"),
        updatedAt: new Date("2023-03-22"),
      },
      {
        id: "loc-008-002",
        universityId: "uni-008",
        city: "Mississauga",
        address: "3359 Mississauga Road, Mississauga, ON L5L 1C6",
        isMainCampus: false,
        createdAt: new Date("2023-03-22"),
        updatedAt: new Date("2023-03-22"),
      },
    ],
    createdAt: new Date("2023-03-22"),
    updatedAt: new Date("2023-03-22"),
  },
  {
    id: "uni-009",
    name: "National University of Singapore",
    country: "Singapore",
    ranking: "Top",
    websiteUrl: "https://www.nus.edu.sg",
    linkedinUrl: "https://www.linkedin.com/school/national-university-of-singapore",
    locations: [
      {
        id: "loc-009-001",
        universityId: "uni-009",
        city: "Singapore",
        address: "21 Lower Kent Ridge Road, Singapore 119077",
        isMainCampus: true,
        createdAt: new Date("2023-04-15"),
        updatedAt: new Date("2023-04-15"),
      },
    ],
    createdAt: new Date("2023-04-15"),
    updatedAt: new Date("2023-04-15"),
  },
  {
    id: "uni-010",
    name: "University of Melbourne",
    country: "Australia",
    ranking: "Top",
    websiteUrl: "https://www.unimelb.edu.au",
    linkedinUrl: "https://www.linkedin.com/school/university-of-melbourne",
    locations: [
      {
        id: "loc-010-001",
        universityId: "uni-010",
        city: "Melbourne",
        address: "Grattan Street, Parkville VIC 3010",
        isMainCampus: true,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
    ],
    createdAt: new Date("2023-05-03"),
    updatedAt: new Date("2023-05-03"),
  },
  {
    id: "uni-011",
    name: "Technical University of Munich",
    country: "Germany",
    ranking: "DPL Favourite",
    websiteUrl: "https://www.tum.de",
    linkedinUrl: "https://www.linkedin.com/school/tu-muenchen",
    locations: [
      {
        id: "loc-011-001",
        universityId: "uni-011",
        city: "Munich",
        address: "Arcisstraße 21, 80333 München",
        isMainCampus: true,
        createdAt: new Date("2023-04-20"),
        updatedAt: new Date("2023-04-20"),
      },
    ],
    createdAt: new Date("2023-04-20"),
    updatedAt: new Date("2023-04-20"),
  },
  {
    id: "uni-012",
    name: "University of Tokyo",
    country: "Japan",
    ranking: "Top",
    websiteUrl: "https://www.u-tokyo.ac.jp/en",
    linkedinUrl: "https://www.linkedin.com/school/university-of-tokyo",
    locations: [
      {
        id: "loc-012-001",
        universityId: "uni-012",
        city: "Tokyo",
        address: "7 Chome-3-1 Hongo, Bunkyo City, Tokyo 113-8654",
        isMainCampus: true,
        createdAt: new Date("2023-05-10"),
        updatedAt: new Date("2023-05-10"),
      },
    ],
    createdAt: new Date("2023-05-10"),
    updatedAt: new Date("2023-05-10"),
  }
]
