import { University } from "@/lib/types/university"

export const sampleUniversities: University[] = [
  {
    id: "uni-001",
    name: "Sir Syed CASE Institute of Technology",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://case.edu.pk/",
    linkedinUrl: "https://pk.linkedin.com/school/sscaseit/",
    locations: [
      {
        id: "loc-001-001",
        universityId: "uni-001",
        city: "Islamabad",
        address: "Street 33, Block A Sector B-17 Multi Gardens B-17, Islamabad",
        isMainCampus: true,
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2023-01-15"),
      },
    ],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-01-15"),
  },
  {
    id: "uni-002",
    name: "National University Of Modern Languages (NUML)",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://numl.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/school/nationaluniversityofmodernlanguages/?originalSubdomain=pk",
    locations: [
      {
        id: "loc-002-001",
        universityId: "uni-002",
        city: "Islamabad",
        address: "H-9/4, Islamabad, Pakistan",
        isMainCampus: true,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
      {
        id: "loc-002-002",
        universityId: "uni-002",
        city: "Lahore",
        address: "1st or 2nd Floor, Aiwan-e-Iqbal, Egerton Road, Lahore",
        isMainCampus: false,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
      {
        id: "loc-002-003",
        universityId: "uni-002",
        city: "Karachi",
        address: "ST # 3, Block K, North Nazimabad Town, Karachi",
        isMainCampus: false,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
      {
        id: "loc-002-004",
        universityId: "uni-002",
        city: "Multan",
        address: "Opposite side of BZU Multan, Multan (Punjab)",
        isMainCampus: false,
        createdAt: new Date("2023-02-10"),
        updatedAt: new Date("2023-02-10"),
      },
    ],
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2023-02-10"),
  },
  {
    id: "uni-003",
    name: "Riphah International University",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://riphah.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/school/riphah-international-university/?originalSubdomain=pk",
    locations: [
      {
        id: "loc-003-001",
        universityId: "uni-003",
        city: "Islamabad",
        address: "Sector I-14, Hajj Complex, Islamabad",
        isMainCampus: true,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-002",
        universityId: "uni-003",
        city: "Islamabad",
        address: "82, Street 19, Block A, Gulberg Greens, Islamabad, Pakistan",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-003",
        universityId: "uni-003",
        city: "Islamabad",
        address: "G-7/4, 7th Avenue, Islamabad",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-004",
        universityId: "uni-003",
        city: "Rawalpindi",
        address: "274 Peshawar Road, Rawalpindi",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-005",
        universityId: "uni-003",
        city: "Lahore",
        address: "13-Km, Raiwind Road, Lahore",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-006",
        universityId: "uni-003",
        city: "Lahore",
        address: "26-M Gulberg-III, Ferozepur Road, Lahore",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-007",
        universityId: "uni-003",
        city: "Malakand",
        address: "Chakdara Road, Malakand",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-008",
        universityId: "uni-003",
        city: "Faisalabad",
        address: "Satiana Road, Faisalabad",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-009",
        universityId: "uni-003",
        city: "Sahiwal",
        address: "Multan Bypass Road, Sahiwal",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-010",
        universityId: "uni-003",
        city: "Peshawar",
        address: "Warsak Road, Peshawar",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "loc-003-011",
        universityId: "uni-003",
        city: "Gujranwala",
        address: "Gondalwala Road, 5-KM from main G.T Road, near GMC, Gujranwala",
        isMainCampus: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
    ],
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "uni-004",
    name: "University of Gujrat",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: null,
    linkedinUrl: "https://www.linkedin.com/school/universityofgujrat/?originalSubdomain=pk",
    locations: [
      {
        id: "loc-004-001",
        universityId: "uni-004",
        city: "Gujrat",
        address: "Jalalpur Jattan Road, Gujrat, Pakistan",
        isMainCampus: true,
        createdAt: new Date("2023-03-05"),
        updatedAt: new Date("2023-03-05"),
      },
      {
        id: "loc-004-002",
        universityId: "uni-004",
        city: "Mandi Bahauddin",
        address: "District Complex, Satsira-DJPS Road, District Mandi Bahauddin, Pakistan",
        isMainCampus: false,
        createdAt: new Date("2023-03-05"),
        updatedAt: new Date("2023-03-05"),
      },
    ],
    createdAt: new Date("2023-03-05"),
    updatedAt: new Date("2023-03-05"),
  },
  {
    id: "uni-005",
    name: "Bahria University",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://www.bahria.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/school/bahria-university/",
    locations: [
      {
        id: "loc-005-001",
        universityId: "uni-005",
        city: "Islamabad",
        address: "Shangrila Road, Sector E-8, Islamabad",
        isMainCampus: true,
        createdAt: new Date("2023-02-28"),
        updatedAt: new Date("2023-02-28"),
      },
      {
        id: "loc-005-002",
        universityId: "uni-005",
        city: "Islamabad",
        address: "Plot 83, H-11/4, Islamabad",
        isMainCampus: false,
        createdAt: new Date("2023-02-28"),
        updatedAt: new Date("2023-02-28"),
      },
      {
        id: "loc-005-003",
        universityId: "uni-005",
        city: "Lahore",
        address: "47-C, Civic Center, Johar Town, Lahore",
        isMainCampus: false,
        createdAt: new Date("2023-02-28"),
        updatedAt: new Date("2023-02-28"),
      },
      {
        id: "loc-005-004",
        universityId: "uni-005",
        city: "Karachi",
        address: "13 National Stadium Road, Karachi",
        isMainCampus: false,
        createdAt: new Date("2023-02-28"),
        updatedAt: new Date("2023-02-28"),
      },
    ],
    createdAt: new Date("2023-02-28"),
    updatedAt: new Date("2023-02-28"),
  },
  {
    id: "uni-006",
    name: "University of Peshawar",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "http://uop.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/school/universityofpeshawar/",
    locations: [
      {
        id: "loc-006-001",
        universityId: "uni-006",
        city: "Peshawar",
        address: "Old Jamrud Road, Peshawar, Khyber Pakhtunkhwa. (Higher Education Commission)",
        isMainCampus: true,
        createdAt: new Date("2023-03-12"),
        updatedAt: new Date("2023-03-12"),
      },
      {
        id: "loc-006-002",
        universityId: "uni-006",
        city: "Abbottabad",
        address: "Bara Gali Campus, Abbottabad-NathiaGali Road, approximately 30 km from Abbottabad. (uop.edu.pk)",
        isMainCampus: false,
        createdAt: new Date("2023-03-12"),
        updatedAt: new Date("2023-03-12"),
      },
    ],
    createdAt: new Date("2023-03-12"),
    updatedAt: new Date("2023-03-12"),
  },
  {
    id: "uni-007",
    name: "Comsats",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://www.comsats.edu.pk/",
    linkedinUrl: null,
    locations: [
      {
        id: "loc-007-001",
        universityId: "uni-007",
        city: "Islamabad",
        address: "Park Road, Tarlai Kalan, Islamabad 45550, Pakistan",
        isMainCampus: true,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
      {
        id: "loc-007-002",
        universityId: "uni-007",
        city: "Abbottabad",
        address: "University Road, Tobe Camp, Abbottabad, Pakistan",
        isMainCampus: false,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
      {
        id: "loc-007-003",
        universityId: "uni-007",
        city: "Lahore",
        address: "Defence Road, Off Raiwind Road, Lahore, Pakistan",
        isMainCampus: false,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
      {
        id: "loc-007-004",
        universityId: "uni-007",
        city: "Wah",
        address: "Wah Cantonment, Pakistan",
        isMainCampus: false,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
      {
        id: "loc-007-005",
        universityId: "uni-007",
        city: "Sahiwal",
        address: null,
        isMainCampus: false,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
      {
        id: "loc-007-006",
        universityId: "uni-007",
        city: "Vehari",
        address: null,
        isMainCampus: false,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
      {
        id: "loc-007-007",
        universityId: "uni-007",
        city: "Attock",
        address: null,
        isMainCampus: false,
        createdAt: new Date("2023-04-08"),
        updatedAt: new Date("2023-04-08"),
      },
    ],
    createdAt: new Date("2023-04-08"),
    updatedAt: new Date("2023-04-08"),
  },
  {
    id: "uni-008",
    name: "Lahore Garrison University",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://admissions.lgu.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/company/lahore-garrison-university/",
    locations: [
      {
        id: "loc-008-001",
        universityId: "uni-008",
        city: "Lahore",
        address: "Sector C, DHA Phase-VI, Lahore, Punjab, Pakistan",
        isMainCampus: true,
        createdAt: new Date("2023-03-22"),
        updatedAt: new Date("2023-03-22"),
      },
    ],
    createdAt: new Date("2023-03-22"),
    updatedAt: new Date("2023-03-22"),
  },
  {
    id: "uni-009",
    name: "UET Taxila",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://www.uettaxila.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/company/uet-taxila/",
    locations: [
      {
        id: "loc-009-001",
        universityId: "uni-009",
        city: "Taxila",
        address: "University of Engineering & Technology, Taxila, 47050, Pakistan",
        isMainCampus: true,
        createdAt: new Date("2023-04-15"),
        updatedAt: new Date("2023-04-15"),
      },
    ],
    createdAt: new Date("2023-04-15"),
    updatedAt: new Date("2023-04-15"),
  },
  {
    id: "uni-010",
    name: "Iqra University",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://iqra.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/school/iqra-university-official/",
    locations: [
      {
        id: "loc-010-001",
        universityId: "uni-010",
        city: "Karachi",
        address: "Shaheed-e-Millat Road, Phase 2 Defence View Housing Society, Karachi",
        isMainCampus: true,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-002",
        universityId: "uni-010",
        city: "Karachi",
        address: "4-B, Block 7 Gulshan-e-Iqbal, Karachi",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-003",
        universityId: "uni-010",
        city: "Karachi",
        address: "Plot No 204-205, Sector 7B/1 North Karachi Town, Karachi",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-004",
        universityId: "uni-010",
        city: "Karachi",
        address: "Gulshan e Amna, Faisal Cantonment (Airport Campus), Karachi",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-005",
        universityId: "uni-010",
        city: "Karachi",
        address: "Sector 8B, Scheme-33, Deh Songal Tappu Gujro, East Karachi (M-9 Campus)",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-006",
        universityId: "uni-010",
        city: "Hyderabad",
        address: "Plot A-26, Off Main Autobahn Road, Hyderabad",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-007",
        universityId: "uni-010",
        city: "Hyderabad",
        address: "Plot A-26, Off Main Autobahn Road, Hyderabad",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-008",
        universityId: "uni-010",
        city: "Islamabad",
        address: "Plot No 5, Khayaban-e-Johar, Sector H-9, Islamabad",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
      {
        id: "loc-010-009",
        universityId: "uni-010",
        city: "Islamabad",
        address: "PIES Complex No 6, Park Road, Chak Shahzad, Tarlai Kalan, Islamabad",
        isMainCampus: false,
        createdAt: new Date("2023-05-03"),
        updatedAt: new Date("2023-05-03"),
      },
    ],
    createdAt: new Date("2023-05-03"),
    updatedAt: new Date("2023-05-03"),
  },
  {
    id: "uni-011",
    name: "Punjab University College of Information Technology",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "https://pucit.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/company/punjab-university-college-of-information-technology-lahore/",
    locations: [
      {
        id: "loc-011-001",
        universityId: "uni-011",
        city: "Lahore",
        address: "Syed Kabeer Ali Shah Road, Canal Bank, Lahore (Quaid-i-Azam Campus / New Campus) of the University of the Punjab",
        isMainCampus: true,
        createdAt: new Date("2023-04-20"),
        updatedAt: new Date("2023-04-20"),
      },
      {
        id: "loc-011-002",
        universityId: "uni-011",
        city: "Lahore",
        address: "Allama Iqbal Campus (Old Campus), University of the Punjab, Lahore",
        isMainCampus: false,
        createdAt: new Date("2023-04-20"),
        updatedAt: new Date("2023-04-20"),
      },
    ],
    createdAt: new Date("2023-04-20"),
    updatedAt: new Date("2023-04-20"),
  },
  {
    id: "uni-012",
    name: "Capital University of Science & Technology (CUST)",
    country: "Pakistan",
    ranking: "Standard",
    websiteUrl: "http://www.cust.edu.pk/",
    linkedinUrl: "https://www.linkedin.com/school/capital-university-of-science-and-technology/",
    locations: [
      {
        id: "loc-012-001",
        universityId: "uni-012",
        city: "Islamabad",
        address: "Islamabad Expressway, Kahuta Road, Zone-V, Islamabad",
        isMainCampus: true,
        createdAt: new Date("2023-05-10"),
        updatedAt: new Date("2023-05-10"),
      },
    ],
    createdAt: new Date("2023-05-10"),
    updatedAt: new Date("2023-05-10"),
  }
]
